// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package client

// Standard header names
const (
	HeaderContentType    = "Content-Type"
	HeaderAccept         = "Accept"
	HeaderAuthorization  = "Authorization"
	HeaderUserAgent      = "User-Agent"
	HeaderXRequestID     = "X-Request-ID"
	HeaderXCorrelationID = "X-Correlation-ID"
)

// Content types
const (
	ContentTypeJSON = "application/json"
	ContentTypeXML  = "application/xml"
	ContentTypeForm = "application/x-www-form-urlencoded"
)

// API-specific headers
const (
	HeaderXRateLimitBucket     = "X-RateLimit-Bucket"
	HeaderXRateLimitLimit      = "X-RateLimit-Limit"
	HeaderXRateLimitRemaining  = "X-RateLimit-Remaining"
	HeaderXRateLimitReset      = "X-RateLimit-Reset"
	HeaderXRateLimitResetAfter = "X-RateLimit-Reset-After"
)

// HeaderValues holds typed header values
type HeaderValues struct {
	XRateLimitBucket     string  // The bucket that the request belongs to
	XRateLimitLimit      int64   // The maximum number of requests that can be made in the current ratelimit window
	XRateLimitRemaining  int64   // The number of requests remaining in the current ratelimit window
	XRateLimitReset      float64 // A unix timestamp in seconds at which the current ratelimit window resets
	XRateLimitResetAfter float64 // The duration in seconds until the current ratelimit window resets
}
