// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package client

import (
	"github.com/kolosys/discord/models"
)

// Response type aliases for common responses
type (
	// EmptyResponse represents a response with no body
	EmptyResponse = struct{}
)

// ClientErrorResponseResponse wraps the ClientErrorResponse response
type ClientErrorResponseResponse struct {
	Data                 models.ErrorResponse
	XRateLimitLimit      string `header:"X-RateLimit-Limit"`
	XRateLimitRemaining  string `header:"X-RateLimit-Remaining"`
	XRateLimitReset      string `header:"X-RateLimit-Reset"`
	XRateLimitResetAfter string `header:"X-RateLimit-Reset-After"`
	XRateLimitBucket     string `header:"X-RateLimit-Bucket"`
}

// ClientRatelimitedResponseResponse wraps the ClientRatelimitedResponse response
type ClientRatelimitedResponseResponse struct {
	Data                 models.RatelimitedResponse
	XRateLimitReset      string `header:"X-RateLimit-Reset"`
	XRateLimitResetAfter string `header:"X-RateLimit-Reset-After"`
	XRateLimitBucket     string `header:"X-RateLimit-Bucket"`
	XRateLimitLimit      string `header:"X-RateLimit-Limit"`
	XRateLimitRemaining  string `header:"X-RateLimit-Remaining"`
}
