// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package client

import (
	"context"
	"net/http"
	"time"

	"github.com/kolosys/neuron"
)

// RESTClient wraps a neuron.Client with generated route methods
type RESTClient struct {
	*neuron.Client
	baseURL string
}

// ClientOptions holds client configuration
type ClientOptions struct {
	BaseURL    string
	UserAgent  string
	Headers    http.Header
	Timeout    time.Duration
	MaxRetries int
}

// NewRESTClient creates a new REST client
func NewRESTClient(opts ClientOptions) *RESTClient {
	if opts.UserAgent == "" {
		opts.UserAgent = "neuron-client/1.0"
	}
	if opts.Timeout == 0 {
		opts.Timeout = 30 * time.Second
	}
	if opts.MaxRetries == 0 {
		opts.MaxRetries = 3
	}

	client := neuron.NewClient(neuron.ClientOptions{
		BaseURL:    opts.BaseURL,
		UserAgent:  opts.UserAgent,
		Headers:    opts.Headers,
		Timeout:    opts.Timeout,
		MaxRetries: opts.MaxRetries,
	})

	return &RESTClient{
		Client:  client,
		baseURL: opts.BaseURL,
	}
}

// BaseURL returns the client's base URL
func (c *RESTClient) BaseURL() string {
	return c.baseURL
}

// WithContext returns a context-aware request builder
func (c *RESTClient) WithContext(ctx context.Context) *RequestBuilder {
	return &RequestBuilder{
		client: c,
		ctx:    ctx,
	}
}

// RequestBuilder helps build requests with context
type RequestBuilder struct {
	client  *RESTClient
	ctx     context.Context
	headers http.Header
	query   map[string]any
}

// WithHeader adds a header to the request
func (b *RequestBuilder) WithHeader(key, value string) *RequestBuilder {
	if b.headers == nil {
		b.headers = make(http.Header)
	}
	b.headers.Set(key, value)
	return b
}

// WithQuery adds a query parameter
func (b *RequestBuilder) WithQuery(key string, value any) *RequestBuilder {
	if b.query == nil {
		b.query = make(map[string]any)
	}
	b.query[key] = value
	return b
}

// Options returns RequestOptions for the builder
func (b *RequestBuilder) Options() *neuron.RequestOptions {
	return &neuron.RequestOptions{
		Context: b.ctx,
		Headers: b.headers,
		Query:   b.query,
	}
}
