// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package client

import (
	"net/http"
)

// Security scheme types
const (
	SecurityTypeHTTP   = "http"
	SecurityTypeAPIKey = "apiKey"
	SecurityTypeOAuth2 = "oauth2"
	SecurityTypeOpenID = "openIdConnect"
)

// SecurityScheme defines a security scheme
type SecurityScheme struct {
	Type         string
	Scheme       string
	BearerFormat string
	In           string
	Name         string
}

// BotTokenSecurity represents the BotToken security scheme
var BotTokenSecurity = SecurityScheme{
	Type: "apiKey",
	In:   "header",
	Name: "Authorization",
}

// OAuth2Security represents the OAuth2 security scheme
var OAuth2Security = SecurityScheme{
	Type: "oauth2",
}

// ApplyBearerToken adds a bearer token to the request headers
func ApplyBearerToken(token string) func(*http.Request) error {
	return func(req *http.Request) error {
		req.Header.Set("Authorization", "Bearer "+token)
		return nil
	}
}

// ApplyAPIKey adds an API key to the request
func ApplyAPIKey(name, value, location string) func(*http.Request) error {
	return func(req *http.Request) error {
		switch location {
		case "header":
			req.Header.Set(name, value)
		case "query":
			q := req.URL.Query()
			q.Set(name, value)
			req.URL.RawQuery = q.Encode()
		case "cookie":
			req.AddCookie(&http.Cookie{Name: name, Value: value})
		}
		return nil
	}
}

// ApplyBasicAuth adds basic authentication to the request
func ApplyBasicAuth(username, password string) func(*http.Request) error {
	return func(req *http.Request) error {
		req.SetBasicAuth(username, password)
		return nil
	}
}
