// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// Account
type Account struct {
	ID   string  `json:"id"`
	Name *string `json:"name,omitempty"`
}
