// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// ActionRowComponent
type ActionRowComponent struct {
	ID         int32 `json:"id"`
	Components []any `json:"components"`
	Type       int32 `json:"type"`
}

// ActionRowComponentForMessageOptions
type ActionRowComponentForMessageOptions struct {
	ID         *int32 `json:"id,omitempty"`
	Components []any  `json:"components"`
	Type       int32  `json:"type"`
}

// ActionRowComponentForModalOptions
type ActionRowComponentForModalOptions struct {
	ID         *int32 `json:"id,omitempty"`
	Components []any  `json:"components"`
	Type       int32  `json:"type"`
}
