// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// AfkTimeouts
type AfkTimeouts int

const (
	AfkTimeouts60   AfkTimeouts = 60
	AfkTimeouts300  AfkTimeouts = 300
	AfkTimeouts900  AfkTimeouts = 900
	AfkTimeouts1800 AfkTimeouts = 1800
	AfkTimeouts3600 AfkTimeouts = 3600
)
