// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// AllowedMentionTypes
type AllowedMentionTypes string

const (
	AllowedMentionTypesUsers    AllowedMentionTypes = "users"
	AllowedMentionTypesRoles    AllowedMentionTypes = "roles"
	AllowedMentionTypesEveryone AllowedMentionTypes = "everyone"
)
