// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// Application
type Application struct {
	ID                     string         `json:"id"`
	Bot                    any            `json:"bot,omitempty"`
	BotPublic              bool           `json:"bot_public,omitempty"`
	BotRequireCodeGrant    bool           `json:"bot_require_code_grant,omitempty"`
	CoverImage             string         `json:"cover_image,omitempty"`
	CustomInstallURL       string         `json:"custom_install_url,omitempty"`
	Description            string         `json:"description"`
	Flags                  int32          `json:"flags"`
	GuildID                string         `json:"guild_id,omitempty"`
	Icon                   *string        `json:"icon,omitempty"`
	InstallParams          any            `json:"install_params,omitempty"`
	IntegrationTypesConfig map[string]any `json:"integration_types_config,omitempty"`
	MaxParticipants        *int32         `json:"max_participants,omitempty"`
	Name                   string         `json:"name"`
	PrimarySkuID           string         `json:"primary_sku_id,omitempty"`
	PrivacyPolicyURL       string         `json:"privacy_policy_url,omitempty"`
	RpcOrigins             []*string      `json:"rpc_origins,omitempty"`
	Slug                   string         `json:"slug,omitempty"`
	Tags                   []string       `json:"tags,omitempty"`
	TermsOfServiceURL      string         `json:"terms_of_service_url,omitempty"`
	Type                   any            `json:"type,omitempty"`
	VerifyKey              string         `json:"verify_key"`
}

// ApplicationCommand
type ApplicationCommand struct {
	ID                       string            `json:"id"`
	ApplicationID            string            `json:"application_id"`
	Contexts                 []int32           `json:"contexts,omitempty"`
	DefaultMemberPermissions *string           `json:"default_member_permissions,omitempty"`
	Description              string            `json:"description"`
	DescriptionLocalizations map[string]string `json:"description_localizations,omitempty"`
	DescriptionLocalized     string            `json:"description_localized,omitempty"`
	DmPermission             bool              `json:"dm_permission,omitempty"`
	GuildID                  string            `json:"guild_id,omitempty"`
	IntegrationTypes         []int32           `json:"integration_types,omitempty"`
	Name                     string            `json:"name"`
	NameLocalizations        map[string]string `json:"name_localizations,omitempty"`
	NameLocalized            string            `json:"name_localized,omitempty"`
	Nsfw                     bool              `json:"nsfw,omitempty"`
	Options                  []any             `json:"options,omitempty"`
	Type                     int32             `json:"type"`
	Version                  string            `json:"version"`
}

// ApplicationCommandAttachmentOption
type ApplicationCommandAttachmentOption struct {
	Description              string            `json:"description"`
	DescriptionLocalizations map[string]string `json:"description_localizations,omitempty"`
	Name                     string            `json:"name"`
	NameLocalizations        map[string]string `json:"name_localizations,omitempty"`
	Required                 *bool             `json:"required,omitempty"`
	Type                     int32             `json:"type"`
}

// ApplicationCommandAutocompleteCallbackOptions
type ApplicationCommandAutocompleteCallbackOptions struct {
	Data any   `json:"data"`
	Type int32 `json:"type"`
}

// ApplicationCommandBooleanOption
type ApplicationCommandBooleanOption struct {
	Description              string            `json:"description"`
	DescriptionLocalizations map[string]string `json:"description_localizations,omitempty"`
	DescriptionLocalized     string            `json:"description_localized,omitempty"`
	Name                     string            `json:"name"`
	NameLocalizations        map[string]string `json:"name_localizations,omitempty"`
	NameLocalized            string            `json:"name_localized,omitempty"`
	Required                 bool              `json:"required,omitempty"`
	Type                     int32             `json:"type"`
}

// ApplicationCommandChannelOption
type ApplicationCommandChannelOption struct {
	ChannelTypes             []int32           `json:"channel_types,omitempty"`
	Description              string            `json:"description"`
	DescriptionLocalizations map[string]string `json:"description_localizations,omitempty"`
	Name                     string            `json:"name"`
	NameLocalizations        map[string]string `json:"name_localizations,omitempty"`
	Required                 *bool             `json:"required,omitempty"`
	Type                     int32             `json:"type"`
}

// ApplicationCommandCreateOptions
type ApplicationCommandCreateOptions struct {
	Contexts                 []int32           `json:"contexts,omitempty"`
	DefaultMemberPermissions *int64            `json:"default_member_permissions,omitempty"`
	Description              *string           `json:"description,omitempty"`
	DescriptionLocalizations map[string]string `json:"description_localizations,omitempty"`
	DmPermission             *bool             `json:"dm_permission,omitempty"`
	Handler                  any               `json:"handler,omitempty"`
	IntegrationTypes         []int32           `json:"integration_types,omitempty"`
	Name                     string            `json:"name"`
	NameLocalizations        map[string]string `json:"name_localizations,omitempty"`
	Options                  []any             `json:"options,omitempty"`
	Type                     any               `json:"type,omitempty"`
}

// ApplicationCommandHandler
type ApplicationCommandHandler struct {
}

// ApplicationCommandIntegerOption
type ApplicationCommandIntegerOption struct {
	Autocomplete             bool              `json:"autocomplete,omitempty"`
	Choices                  []any             `json:"choices,omitempty"`
	Description              string            `json:"description"`
	DescriptionLocalizations map[string]string `json:"description_localizations,omitempty"`
	DescriptionLocalized     string            `json:"description_localized,omitempty"`
	MaxValue                 int64             `json:"max_value,omitempty"`
	MinValue                 int64             `json:"min_value,omitempty"`
	Name                     string            `json:"name"`
	NameLocalizations        map[string]string `json:"name_localizations,omitempty"`
	NameLocalized            string            `json:"name_localized,omitempty"`
	Required                 bool              `json:"required,omitempty"`
	Type                     int32             `json:"type"`
}

// ApplicationCommandInteractionMetadata
type ApplicationCommandInteractionMetadata struct {
	ID                           string            `json:"id"`
	AuthorizingIntegrationOwners map[string]string `json:"authorizing_integration_owners"`
	OriginalResponseMessageID    string            `json:"original_response_message_id,omitempty"`
	TargetMessageID              string            `json:"target_message_id,omitempty"`
	TargetUser                   any               `json:"target_user,omitempty"`
	Type                         int32             `json:"type"`
	User                         any               `json:"user,omitempty"`
}

// ApplicationCommandMentionableOption
type ApplicationCommandMentionableOption struct {
	Description              string            `json:"description"`
	DescriptionLocalizations map[string]string `json:"description_localizations,omitempty"`
	Name                     string            `json:"name"`
	NameLocalizations        map[string]string `json:"name_localizations,omitempty"`
	Required                 *bool             `json:"required,omitempty"`
	Type                     int32             `json:"type"`
}

// ApplicationCommandNumberOption
type ApplicationCommandNumberOption struct {
	Autocomplete             bool              `json:"autocomplete,omitempty"`
	Choices                  []any             `json:"choices,omitempty"`
	Description              string            `json:"description"`
	DescriptionLocalizations map[string]string `json:"description_localizations,omitempty"`
	DescriptionLocalized     string            `json:"description_localized,omitempty"`
	MaxValue                 float64           `json:"max_value,omitempty"`
	MinValue                 float64           `json:"min_value,omitempty"`
	Name                     string            `json:"name"`
	NameLocalizations        map[string]string `json:"name_localizations,omitempty"`
	NameLocalized            string            `json:"name_localized,omitempty"`
	Required                 bool              `json:"required,omitempty"`
	Type                     int32             `json:"type"`
}

// ApplicationCommandOptionIntegerChoice
type ApplicationCommandOptionIntegerChoice struct {
	Name              string            `json:"name"`
	NameLocalizations map[string]string `json:"name_localizations,omitempty"`
	NameLocalized     string            `json:"name_localized,omitempty"`
	Value             int64             `json:"value"`
}

// ApplicationCommandOptionNumberChoice
type ApplicationCommandOptionNumberChoice struct {
	Name              string            `json:"name"`
	NameLocalizations map[string]string `json:"name_localizations,omitempty"`
	NameLocalized     string            `json:"name_localized,omitempty"`
	Value             float64           `json:"value"`
}

// ApplicationCommandOptionStringChoice
type ApplicationCommandOptionStringChoice struct {
	Name              string            `json:"name"`
	NameLocalizations map[string]string `json:"name_localizations,omitempty"`
	Value             string            `json:"value"`
}

// ApplicationCommandOptionType
type ApplicationCommandOptionType int

const (
	ApplicationCommandOptionType1  ApplicationCommandOptionType = 1
	ApplicationCommandOptionType2  ApplicationCommandOptionType = 2
	ApplicationCommandOptionType3  ApplicationCommandOptionType = 3
	ApplicationCommandOptionType4  ApplicationCommandOptionType = 4
	ApplicationCommandOptionType5  ApplicationCommandOptionType = 5
	ApplicationCommandOptionType6  ApplicationCommandOptionType = 6
	ApplicationCommandOptionType7  ApplicationCommandOptionType = 7
	ApplicationCommandOptionType8  ApplicationCommandOptionType = 8
	ApplicationCommandOptionType9  ApplicationCommandOptionType = 9
	ApplicationCommandOptionType10 ApplicationCommandOptionType = 10
	ApplicationCommandOptionType11 ApplicationCommandOptionType = 11
)

// ApplicationCommandPatchOptionsPartial
type ApplicationCommandPatchOptionsPartial struct {
	Contexts                 []int32           `json:"contexts,omitempty"`
	DefaultMemberPermissions *int64            `json:"default_member_permissions,omitempty"`
	Description              *string           `json:"description,omitempty"`
	DescriptionLocalizations map[string]string `json:"description_localizations,omitempty"`
	DmPermission             *bool             `json:"dm_permission,omitempty"`
	Handler                  any               `json:"handler,omitempty"`
	IntegrationTypes         []int32           `json:"integration_types,omitempty"`
	Name                     string            `json:"name,omitempty"`
	NameLocalizations        map[string]string `json:"name_localizations,omitempty"`
	Options                  []any             `json:"options,omitempty"`
}

// ApplicationCommandPermission
type ApplicationCommandPermission struct {
	ID         string `json:"id"`
	Permission bool   `json:"permission"`
	Type       int32  `json:"type"`
}

// ApplicationCommandPermissionType
type ApplicationCommandPermissionType int

const (
	ApplicationCommandPermissionType1 ApplicationCommandPermissionType = 1
	ApplicationCommandPermissionType2 ApplicationCommandPermissionType = 2
	ApplicationCommandPermissionType3 ApplicationCommandPermissionType = 3
)

// ApplicationCommandRoleOption
type ApplicationCommandRoleOption struct {
	Description              string            `json:"description"`
	DescriptionLocalizations map[string]string `json:"description_localizations,omitempty"`
	Name                     string            `json:"name"`
	NameLocalizations        map[string]string `json:"name_localizations,omitempty"`
	Required                 *bool             `json:"required,omitempty"`
	Type                     int32             `json:"type"`
}

// ApplicationCommandStringOption
type ApplicationCommandStringOption struct {
	Autocomplete             bool              `json:"autocomplete,omitempty"`
	Choices                  []any             `json:"choices,omitempty"`
	Description              string            `json:"description"`
	DescriptionLocalizations map[string]string `json:"description_localizations,omitempty"`
	DescriptionLocalized     string            `json:"description_localized,omitempty"`
	MaxLength                int32             `json:"max_length,omitempty"`
	MinLength                int32             `json:"min_length,omitempty"`
	Name                     string            `json:"name"`
	NameLocalizations        map[string]string `json:"name_localizations,omitempty"`
	NameLocalized            string            `json:"name_localized,omitempty"`
	Required                 bool              `json:"required,omitempty"`
	Type                     int32             `json:"type"`
}

// ApplicationCommandSubcommandGroupOption
type ApplicationCommandSubcommandGroupOption struct {
	Description              string            `json:"description"`
	DescriptionLocalizations map[string]string `json:"description_localizations,omitempty"`
	DescriptionLocalized     string            `json:"description_localized,omitempty"`
	Name                     string            `json:"name"`
	NameLocalizations        map[string]string `json:"name_localizations,omitempty"`
	NameLocalized            string            `json:"name_localized,omitempty"`
	Options                  []any             `json:"options,omitempty"`
	Required                 bool              `json:"required,omitempty"`
	Type                     int32             `json:"type"`
}

// ApplicationCommandSubcommandOption
type ApplicationCommandSubcommandOption struct {
	Description              string            `json:"description"`
	DescriptionLocalizations map[string]string `json:"description_localizations,omitempty"`
	Name                     string            `json:"name"`
	NameLocalizations        map[string]string `json:"name_localizations,omitempty"`
	Options                  []any             `json:"options,omitempty"`
	Required                 *bool             `json:"required,omitempty"`
	Type                     int32             `json:"type"`
}

// ApplicationCommandType
type ApplicationCommandType int

const (
	ApplicationCommandType1 ApplicationCommandType = 1
	ApplicationCommandType2 ApplicationCommandType = 2
	ApplicationCommandType3 ApplicationCommandType = 3
	ApplicationCommandType4 ApplicationCommandType = 4
)

// ApplicationCommandUpdateOptions
type ApplicationCommandUpdateOptions struct {
	ID                       any               `json:"id,omitempty"`
	Contexts                 []int32           `json:"contexts,omitempty"`
	DefaultMemberPermissions *int64            `json:"default_member_permissions,omitempty"`
	Description              *string           `json:"description,omitempty"`
	DescriptionLocalizations map[string]string `json:"description_localizations,omitempty"`
	DmPermission             *bool             `json:"dm_permission,omitempty"`
	Handler                  any               `json:"handler,omitempty"`
	IntegrationTypes         []int32           `json:"integration_types,omitempty"`
	Name                     string            `json:"name"`
	NameLocalizations        map[string]string `json:"name_localizations,omitempty"`
	Options                  []any             `json:"options,omitempty"`
	Type                     any               `json:"type,omitempty"`
}

// ApplicationCommandUserOption
type ApplicationCommandUserOption struct {
	Description              string            `json:"description"`
	DescriptionLocalizations map[string]string `json:"description_localizations,omitempty"`
	DescriptionLocalized     string            `json:"description_localized,omitempty"`
	Name                     string            `json:"name"`
	NameLocalizations        map[string]string `json:"name_localizations,omitempty"`
	NameLocalized            string            `json:"name_localized,omitempty"`
	Required                 bool              `json:"required,omitempty"`
	Type                     int32             `json:"type"`
}

// ApplicationExplicitContentFilterTypes
type ApplicationExplicitContentFilterTypes int

const (
	ApplicationExplicitContentFilterTypes0 ApplicationExplicitContentFilterTypes = 0
	ApplicationExplicitContentFilterTypes1 ApplicationExplicitContentFilterTypes = 1
)

// ApplicationFormPartial
type ApplicationFormPartial struct {
	CoverImage                     *string        `json:"cover_image,omitempty"`
	CustomInstallURL               *string        `json:"custom_install_url,omitempty"`
	Description                    any            `json:"description,omitempty"`
	ExplicitContentFilter          any            `json:"explicit_content_filter,omitempty"`
	Flags                          *int64         `json:"flags,omitempty"`
	Icon                           *string        `json:"icon,omitempty"`
	InstallParams                  any            `json:"install_params,omitempty"`
	IntegrationTypesConfig         map[string]any `json:"integration_types_config,omitempty"`
	InteractionsEndpointURL        *string        `json:"interactions_endpoint_url,omitempty"`
	MaxParticipants                *int32         `json:"max_participants,omitempty"`
	RoleConnectionsVerificationURL *string        `json:"role_connections_verification_url,omitempty"`
	Tags                           []string       `json:"tags,omitempty"`
	TeamID                         any            `json:"team_id,omitempty"`
	Type                           any            `json:"type,omitempty"`
}

// ApplicationIdentityProviderAuthType
type ApplicationIdentityProviderAuthType string

const (
	ApplicationIdentityProviderAuthTypeOIDC                          ApplicationIdentityProviderAuthType = "OIDC"
	ApplicationIdentityProviderAuthTypeEPICONLINESERVICESACCESSTOKEN ApplicationIdentityProviderAuthType = "EPIC_ONLINE_SERVICES_ACCESS_TOKEN"
	ApplicationIdentityProviderAuthTypeEPICONLINESERVICESIDTOKEN     ApplicationIdentityProviderAuthType = "EPIC_ONLINE_SERVICES_ID_TOKEN"
	ApplicationIdentityProviderAuthTypeSTEAMSESSIONTICKET            ApplicationIdentityProviderAuthType = "STEAM_SESSION_TICKET"
	ApplicationIdentityProviderAuthTypeUNITYSERVICESIDTOKEN          ApplicationIdentityProviderAuthType = "UNITY_SERVICES_ID_TOKEN"
	ApplicationIdentityProviderAuthTypeDISCORDBOTISSUEDACCESSTOKEN   ApplicationIdentityProviderAuthType = "DISCORD_BOT_ISSUED_ACCESS_TOKEN"
	ApplicationIdentityProviderAuthTypeAPPLEIDTOKEN                  ApplicationIdentityProviderAuthType = "APPLE_ID_TOKEN"
	ApplicationIdentityProviderAuthTypePLAYSTATIONNETWORKIDTOKEN     ApplicationIdentityProviderAuthType = "PLAYSTATION_NETWORK_ID_TOKEN"
)

// ApplicationIncomingWebhook
type ApplicationIncomingWebhook struct {
	ID            string  `json:"id"`
	ApplicationID any     `json:"application_id,omitempty"`
	Avatar        *string `json:"avatar,omitempty"`
	ChannelID     any     `json:"channel_id,omitempty"`
	GuildID       any     `json:"guild_id,omitempty"`
	Name          string  `json:"name"`
	Type          int32   `json:"type"`
	User          any     `json:"user,omitempty"`
}

// ApplicationIntegrationType
type ApplicationIntegrationType int

const (
	ApplicationIntegrationType0 ApplicationIntegrationType = 0
	ApplicationIntegrationType1 ApplicationIntegrationType = 1
)

// ApplicationIntegrationTypeConfiguration
type ApplicationIntegrationTypeConfiguration struct {
	Oauth2InstallParams any `json:"oauth2_install_params,omitempty"`
}

// ApplicationOAuth2InstallParams
type ApplicationOAuth2InstallParams struct {
	Permissions *int64   `json:"permissions,omitempty"`
	Scopes      []string `json:"scopes,omitempty"`
}

// ApplicationRoleConnectionsMetadataItem
type ApplicationRoleConnectionsMetadataItem struct {
	Description              string            `json:"description"`
	DescriptionLocalizations map[string]string `json:"description_localizations,omitempty"`
	Key                      string            `json:"key"`
	Name                     string            `json:"name"`
	NameLocalizations        map[string]string `json:"name_localizations,omitempty"`
	Type                     int32             `json:"type"`
}

// ApplicationRoleConnectionsMetadataItemOptions
type ApplicationRoleConnectionsMetadataItemOptions struct {
	Description              string             `json:"description"`
	DescriptionLocalizations map[string]*string `json:"description_localizations,omitempty"`
	Key                      string             `json:"key"`
	Name                     string             `json:"name"`
	NameLocalizations        map[string]*string `json:"name_localizations,omitempty"`
	Type                     int32              `json:"type"`
}

// ApplicationTypes
type ApplicationTypes int

const (
	ApplicationTypes4 ApplicationTypes = 4
)

// ApplicationUserRoleConnection
type ApplicationUserRoleConnection struct {
	Metadata         map[string]string `json:"metadata,omitempty"`
	PlatformName     *string           `json:"platform_name,omitempty"`
	PlatformUsername *string           `json:"platform_username,omitempty"`
}
