// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// Attachment
type Attachment struct {
	ID               string    `json:"id"`
	Application      any       `json:"application,omitempty"`
	ClipCreatedAt    time.Time `json:"clip_created_at,omitempty"`
	ClipParticipants []any     `json:"clip_participants,omitempty"`
	ContentType      string    `json:"content_type,omitempty"`
	Description      string    `json:"description,omitempty"`
	DurationSecs     float64   `json:"duration_secs,omitempty"`
	Ephemeral        bool      `json:"ephemeral,omitempty"`
	Filename         string    `json:"filename"`
	Height           int32     `json:"height,omitempty"`
	ProxyURL         string    `json:"proxy_url"`
	Size             int32     `json:"size"`
	Title            *string   `json:"title,omitempty"`
	URL              string    `json:"url"`
	Waveform         string    `json:"waveform,omitempty"`
	Width            int32     `json:"width,omitempty"`
}
