// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// AuditLogActionTypes
type AuditLogActionTypes int

const (
	AuditLogActionTypes1   AuditLogActionTypes = 1
	AuditLogActionTypes10  AuditLogActionTypes = 10
	AuditLogActionTypes11  AuditLogActionTypes = 11
	AuditLogActionTypes12  AuditLogActionTypes = 12
	AuditLogActionTypes13  AuditLogActionTypes = 13
	AuditLogActionTypes14  AuditLogActionTypes = 14
	AuditLogActionTypes15  AuditLogActionTypes = 15
	AuditLogActionTypes20  AuditLogActionTypes = 20
	AuditLogActionTypes21  AuditLogActionTypes = 21
	AuditLogActionTypes22  AuditLogActionTypes = 22
	AuditLogActionTypes23  AuditLogActionTypes = 23
	AuditLogActionTypes24  AuditLogActionTypes = 24
	AuditLogActionTypes25  AuditLogActionTypes = 25
	AuditLogActionTypes26  AuditLogActionTypes = 26
	AuditLogActionTypes27  AuditLogActionTypes = 27
	AuditLogActionTypes28  AuditLogActionTypes = 28
	AuditLogActionTypes30  AuditLogActionTypes = 30
	AuditLogActionTypes31  AuditLogActionTypes = 31
	AuditLogActionTypes32  AuditLogActionTypes = 32
	AuditLogActionTypes40  AuditLogActionTypes = 40
	AuditLogActionTypes41  AuditLogActionTypes = 41
	AuditLogActionTypes42  AuditLogActionTypes = 42
	AuditLogActionTypes50  AuditLogActionTypes = 50
	AuditLogActionTypes51  AuditLogActionTypes = 51
	AuditLogActionTypes52  AuditLogActionTypes = 52
	AuditLogActionTypes60  AuditLogActionTypes = 60
	AuditLogActionTypes61  AuditLogActionTypes = 61
	AuditLogActionTypes62  AuditLogActionTypes = 62
	AuditLogActionTypes72  AuditLogActionTypes = 72
	AuditLogActionTypes73  AuditLogActionTypes = 73
	AuditLogActionTypes74  AuditLogActionTypes = 74
	AuditLogActionTypes75  AuditLogActionTypes = 75
	AuditLogActionTypes80  AuditLogActionTypes = 80
	AuditLogActionTypes81  AuditLogActionTypes = 81
	AuditLogActionTypes82  AuditLogActionTypes = 82
	AuditLogActionTypes83  AuditLogActionTypes = 83
	AuditLogActionTypes84  AuditLogActionTypes = 84
	AuditLogActionTypes85  AuditLogActionTypes = 85
	AuditLogActionTypes90  AuditLogActionTypes = 90
	AuditLogActionTypes91  AuditLogActionTypes = 91
	AuditLogActionTypes92  AuditLogActionTypes = 92
	AuditLogActionTypes100 AuditLogActionTypes = 100
	AuditLogActionTypes101 AuditLogActionTypes = 101
	AuditLogActionTypes102 AuditLogActionTypes = 102
	AuditLogActionTypes110 AuditLogActionTypes = 110
	AuditLogActionTypes111 AuditLogActionTypes = 111
	AuditLogActionTypes112 AuditLogActionTypes = 112
	AuditLogActionTypes121 AuditLogActionTypes = 121
	AuditLogActionTypes130 AuditLogActionTypes = 130
	AuditLogActionTypes131 AuditLogActionTypes = 131
	AuditLogActionTypes132 AuditLogActionTypes = 132
	AuditLogActionTypes140 AuditLogActionTypes = 140
	AuditLogActionTypes141 AuditLogActionTypes = 141
	AuditLogActionTypes142 AuditLogActionTypes = 142
	AuditLogActionTypes143 AuditLogActionTypes = 143
	AuditLogActionTypes144 AuditLogActionTypes = 144
	AuditLogActionTypes145 AuditLogActionTypes = 145
	AuditLogActionTypes146 AuditLogActionTypes = 146
	AuditLogActionTypes150 AuditLogActionTypes = 150
	AuditLogActionTypes151 AuditLogActionTypes = 151
	AuditLogActionTypes163 AuditLogActionTypes = 163
	AuditLogActionTypes164 AuditLogActionTypes = 164
	AuditLogActionTypes165 AuditLogActionTypes = 165
	AuditLogActionTypes166 AuditLogActionTypes = 166
	AuditLogActionTypes167 AuditLogActionTypes = 167
	AuditLogActionTypes171 AuditLogActionTypes = 171
	AuditLogActionTypes172 AuditLogActionTypes = 172
	AuditLogActionTypes180 AuditLogActionTypes = 180
	AuditLogActionTypes190 AuditLogActionTypes = 190
	AuditLogActionTypes191 AuditLogActionTypes = 191
	AuditLogActionTypes192 AuditLogActionTypes = 192
	AuditLogActionTypes193 AuditLogActionTypes = 193
	AuditLogActionTypes211 AuditLogActionTypes = 211
)

// AuditLogEntry
type AuditLogEntry struct {
	ID         string            `json:"id"`
	ActionType int32             `json:"action_type"`
	Changes    []any             `json:"changes,omitempty"`
	Options    map[string]string `json:"options,omitempty"`
	Reason     string            `json:"reason,omitempty"`
	TargetID   any               `json:"target_id,omitempty"`
	UserID     any               `json:"user_id,omitempty"`
}

// AuditLogObjectChange
type AuditLogObjectChange struct {
	Key      *string `json:"key,omitempty"`
	NewValue any     `json:"new_value,omitempty"`
	OldValue any     `json:"old_value,omitempty"`
}
