// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// AutomodActionType
type AutomodActionType int

const (
	AutomodActionType1 AutomodActionType = 1
	AutomodActionType2 AutomodActionType = 2
	AutomodActionType3 AutomodActionType = 3
	AutomodActionType4 AutomodActionType = 4
)

// AutomodEventType
type AutomodEventType int

const (
	AutomodEventType1 AutomodEventType = 1
	AutomodEventType2 AutomodEventType = 2
)

// AutomodKeywordPresetType
type AutomodKeywordPresetType int

const (
	AutomodKeywordPresetType1 AutomodKeywordPresetType = 1
	AutomodKeywordPresetType2 AutomodKeywordPresetType = 2
	AutomodKeywordPresetType3 AutomodKeywordPresetType = 3
)

// AutomodTriggerType
type AutomodTriggerType int

const (
	AutomodTriggerType1 AutomodTriggerType = 1
	AutomodTriggerType2 AutomodTriggerType = 2
	AutomodTriggerType3 AutomodTriggerType = 3
	AutomodTriggerType4 AutomodTriggerType = 4
	AutomodTriggerType5 AutomodTriggerType = 5
)
