// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// AvailableLocalesEnum
type AvailableLocalesEnum string

const (
	AvailableLocalesEnumAr    AvailableLocalesEnum = "ar"
	AvailableLocalesEnumBg    AvailableLocalesEnum = "bg"
	AvailableLocalesEnumCs    AvailableLocalesEnum = "cs"
	AvailableLocalesEnumDa    AvailableLocalesEnum = "da"
	AvailableLocalesEnumDe    AvailableLocalesEnum = "de"
	AvailableLocalesEnumEl    AvailableLocalesEnum = "el"
	AvailableLocalesEnumEnGB  AvailableLocalesEnum = "en-GB"
	AvailableLocalesEnumEnUS  AvailableLocalesEnum = "en-US"
	AvailableLocalesEnumEs419 AvailableLocalesEnum = "es-419"
	AvailableLocalesEnumEsES  AvailableLocalesEnum = "es-ES"
	AvailableLocalesEnumFi    AvailableLocalesEnum = "fi"
	AvailableLocalesEnumFr    AvailableLocalesEnum = "fr"
	AvailableLocalesEnumHe    AvailableLocalesEnum = "he"
	AvailableLocalesEnumHi    AvailableLocalesEnum = "hi"
	AvailableLocalesEnumHr    AvailableLocalesEnum = "hr"
	AvailableLocalesEnumHu    AvailableLocalesEnum = "hu"
	AvailableLocalesEnumID    AvailableLocalesEnum = "id"
	AvailableLocalesEnumIt    AvailableLocalesEnum = "it"
	AvailableLocalesEnumJa    AvailableLocalesEnum = "ja"
	AvailableLocalesEnumKo    AvailableLocalesEnum = "ko"
	AvailableLocalesEnumLt    AvailableLocalesEnum = "lt"
	AvailableLocalesEnumNl    AvailableLocalesEnum = "nl"
	AvailableLocalesEnumNo    AvailableLocalesEnum = "no"
	AvailableLocalesEnumPl    AvailableLocalesEnum = "pl"
	AvailableLocalesEnumPtBR  AvailableLocalesEnum = "pt-BR"
	AvailableLocalesEnumRo    AvailableLocalesEnum = "ro"
	AvailableLocalesEnumRu    AvailableLocalesEnum = "ru"
	AvailableLocalesEnumSvSE  AvailableLocalesEnum = "sv-SE"
	AvailableLocalesEnumTh    AvailableLocalesEnum = "th"
	AvailableLocalesEnumTr    AvailableLocalesEnum = "tr"
	AvailableLocalesEnumUk    AvailableLocalesEnum = "uk"
	AvailableLocalesEnumVi    AvailableLocalesEnum = "vi"
	AvailableLocalesEnumZhCN  AvailableLocalesEnum = "zh-CN"
	AvailableLocalesEnumZhTW  AvailableLocalesEnum = "zh-TW"
)
