// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// BanUserFromGuildOptions
type BanUserFromGuildOptions struct {
	DeleteMessageDays    *int64 `json:"delete_message_days,omitempty"`
	DeleteMessageSeconds *int64 `json:"delete_message_seconds,omitempty"`
}
