// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// BaseCreateMessageCreateOptions
type BaseCreateMessageCreateOptions struct {
	AllowedMentions   any      `json:"allowed_mentions,omitempty"`
	Attachments       []any    `json:"attachments,omitempty"`
	Components        []any    `json:"components,omitempty"`
	ConfettiPotion    any      `json:"confetti_potion,omitempty"`
	Content           *string  `json:"content,omitempty"`
	Embeds            []any    `json:"embeds,omitempty"`
	Flags             *int64   `json:"flags,omitempty"`
	Poll              any      `json:"poll,omitempty"`
	SharedClientTheme any      `json:"shared_client_theme,omitempty"`
	StickerIds        []string `json:"sticker_ids,omitempty"`
}
