// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// BasicApplication
type BasicApplication struct {
	ID           string  `json:"id"`
	Bot          any     `json:"bot,omitempty"`
	CoverImage   string  `json:"cover_image,omitempty"`
	Description  string  `json:"description"`
	Icon         *string `json:"icon,omitempty"`
	Name         string  `json:"name"`
	PrimarySkuID string  `json:"primary_sku_id,omitempty"`
	Type         any     `json:"type,omitempty"`
}

// BasicGuildMember
type BasicGuildMember struct {
	Avatar                     *string    `json:"avatar,omitempty"`
	AvatarDecorationData       any        `json:"avatar_decoration_data,omitempty"`
	Banner                     *string    `json:"banner,omitempty"`
	Collectibles               any        `json:"collectibles,omitempty"`
	CommunicationDisabledUntil *time.Time `json:"communication_disabled_until,omitempty"`
	Flags                      int32      `json:"flags"`
	JoinedAt                   time.Time  `json:"joined_at"`
	Nick                       *string    `json:"nick,omitempty"`
	Pending                    bool       `json:"pending"`
	PremiumSince               *time.Time `json:"premium_since,omitempty"`
	Roles                      []string   `json:"roles"`
}

// BasicMessage
type BasicMessage struct {
	ID                   string     `json:"id"`
	Activity             any        `json:"activity,omitempty"`
	Application          any        `json:"application,omitempty"`
	ApplicationID        string     `json:"application_id,omitempty"`
	Attachments          []any      `json:"attachments"`
	Author               any        `json:"author"`
	Call                 any        `json:"call,omitempty"`
	ChannelID            string     `json:"channel_id"`
	Components           []any      `json:"components"`
	Content              string     `json:"content"`
	EditedTimestamp      *time.Time `json:"edited_timestamp,omitempty"`
	Embeds               []any      `json:"embeds"`
	Flags                int32      `json:"flags"`
	Interaction          any        `json:"interaction,omitempty"`
	InteractionMetadata  any        `json:"interaction_metadata,omitempty"`
	MentionChannels      []any      `json:"mention_channels,omitempty"`
	MentionEveryone      bool       `json:"mention_everyone"`
	MentionRoles         []string   `json:"mention_roles"`
	Mentions             []any      `json:"mentions"`
	MessageReference     any        `json:"message_reference,omitempty"`
	MessageSnapshots     []any      `json:"message_snapshots,omitempty"`
	Nonce                any        `json:"nonce,omitempty"`
	Pinned               bool       `json:"pinned"`
	Poll                 any        `json:"poll,omitempty"`
	Position             int32      `json:"position,omitempty"`
	PurchaseNotification any        `json:"purchase_notification,omitempty"`
	Resolved             any        `json:"resolved,omitempty"`
	RoleSubscriptionData any        `json:"role_subscription_data,omitempty"`
	SharedClientTheme    any        `json:"shared_client_theme,omitempty"`
	StickerItems         []any      `json:"sticker_items,omitempty"`
	Stickers             []any      `json:"stickers,omitempty"`
	Thread               any        `json:"thread,omitempty"`
	Timestamp            time.Time  `json:"timestamp"`
	Tts                  bool       `json:"tts"`
	Type                 int32      `json:"type"`
	WebhookID            string     `json:"webhook_id,omitempty"`
}
