// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// BlockMessageAction
type BlockMessageAction struct {
	Metadata any   `json:"metadata"`
	Type     int32 `json:"type"`
}

// BlockMessageActionMetadata
type BlockMessageActionMetadata struct {
	CustomMessage string `json:"custom_message,omitempty"`
}
