// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// BotAccountPatchOptions
type BotAccountPatchOptions struct {
	Avatar   *string `json:"avatar,omitempty"`
	Banner   *string `json:"banner,omitempty"`
	Username string  `json:"username"`
}

// BotAddGuildMemberOptions
type BotAddGuildMemberOptions struct {
	AccessToken string   `json:"access_token"`
	Deaf        *bool    `json:"deaf,omitempty"`
	Flags       *int64   `json:"flags,omitempty"`
	Mute        *bool    `json:"mute,omitempty"`
	Nick        *string  `json:"nick,omitempty"`
	Roles       []string `json:"roles,omitempty"`
}
