// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// BulkBanUsers
type BulkBanUsers struct {
	BannedUsers []string `json:"banned_users"`
	FailedUsers []string `json:"failed_users"`
}

// BulkBanUsersOptions
type BulkBanUsersOptions struct {
	DeleteMessageSeconds *int64   `json:"delete_message_seconds,omitempty"`
	UserIds              []string `json:"user_ids"`
}

// BulkLobbyMemberOptions
type BulkLobbyMemberOptions struct {
	ID           string            `json:"id"`
	Flags        any               `json:"flags,omitempty"`
	Metadata     map[string]string `json:"metadata,omitempty"`
	RemoveMember *bool             `json:"remove_member,omitempty"`
}
