// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// ButtonComponent
type ButtonComponent struct {
	ID       int32   `json:"id"`
	CustomID string  `json:"custom_id,omitempty"`
	Disabled bool    `json:"disabled,omitempty"`
	Emoji    any     `json:"emoji,omitempty"`
	Label    string  `json:"label,omitempty"`
	SkuID    string  `json:"sku_id,omitempty"`
	Style    int32   `json:"style"`
	Type     int32   `json:"type"`
	URL      *string `json:"url,omitempty"`
}

// ButtonComponentForMessageOptions
type ButtonComponentForMessageOptions struct {
	ID       *int32  `json:"id,omitempty"`
	CustomID *string `json:"custom_id,omitempty"`
	Disabled *bool   `json:"disabled,omitempty"`
	Emoji    any     `json:"emoji,omitempty"`
	Label    *string `json:"label,omitempty"`
	SkuID    any     `json:"sku_id,omitempty"`
	Style    int32   `json:"style"`
	Type     int32   `json:"type"`
	URL      *string `json:"url,omitempty"`
}

// ButtonStyleTypes
type ButtonStyleTypes int

const (
	ButtonStyleTypes1 ButtonStyleTypes = 1
	ButtonStyleTypes2 ButtonStyleTypes = 2
	ButtonStyleTypes3 ButtonStyleTypes = 3
	ButtonStyleTypes4 ButtonStyleTypes = 4
	ButtonStyleTypes5 ButtonStyleTypes = 5
	ButtonStyleTypes6 ButtonStyleTypes = 6
)
