// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// ChannelFollower
type ChannelFollower struct {
	ChannelID string `json:"channel_id"`
	WebhookID string `json:"webhook_id"`
}

// ChannelFollowerWebhook
type ChannelFollowerWebhook struct {
	ID            string  `json:"id"`
	ApplicationID any     `json:"application_id,omitempty"`
	Avatar        *string `json:"avatar,omitempty"`
	ChannelID     any     `json:"channel_id,omitempty"`
	GuildID       any     `json:"guild_id,omitempty"`
	Name          string  `json:"name"`
	SourceChannel any     `json:"source_channel,omitempty"`
	SourceGuild   any     `json:"source_guild,omitempty"`
	Type          int32   `json:"type"`
	User          any     `json:"user,omitempty"`
}

// ChannelPermissionOverwrite
type ChannelPermissionOverwrite struct {
	ID    string `json:"id"`
	Allow string `json:"allow"`
	Deny  string `json:"deny"`
	Type  int32  `json:"type"`
}

// ChannelPermissionOverwriteOptions
type ChannelPermissionOverwriteOptions struct {
	ID    string `json:"id"`
	Allow *int64 `json:"allow,omitempty"`
	Deny  *int64 `json:"deny,omitempty"`
	Type  any    `json:"type,omitempty"`
}

// ChannelPermissionOverwrites
type ChannelPermissionOverwrites int

const (
	ChannelPermissionOverwrites0 ChannelPermissionOverwrites = 0
	ChannelPermissionOverwrites1 ChannelPermissionOverwrites = 1
)

// ChannelSelectComponent
type ChannelSelectComponent struct {
	ID            int32   `json:"id"`
	ChannelTypes  []int32 `json:"channel_types,omitempty"`
	CustomID      string  `json:"custom_id"`
	DefaultValues []any   `json:"default_values,omitempty"`
	Disabled      bool    `json:"disabled,omitempty"`
	MaxValues     *int32  `json:"max_values,omitempty"`
	MinValues     *int32  `json:"min_values,omitempty"`
	Placeholder   string  `json:"placeholder,omitempty"`
	Type          int32   `json:"type"`
}

// ChannelSelectComponentForMessageOptions
type ChannelSelectComponentForMessageOptions struct {
	ID            *int32  `json:"id,omitempty"`
	ChannelTypes  []int32 `json:"channel_types,omitempty"`
	CustomID      string  `json:"custom_id"`
	DefaultValues []any   `json:"default_values,omitempty"`
	Disabled      *bool   `json:"disabled,omitempty"`
	MaxValues     *int64  `json:"max_values,omitempty"`
	MinValues     *int64  `json:"min_values,omitempty"`
	Placeholder   *string `json:"placeholder,omitempty"`
	Required      *bool   `json:"required,omitempty"`
	Type          int32   `json:"type"`
}

// ChannelSelectComponentForModalOptions
type ChannelSelectComponentForModalOptions struct {
	ID            *int32  `json:"id,omitempty"`
	ChannelTypes  []int32 `json:"channel_types,omitempty"`
	CustomID      string  `json:"custom_id"`
	DefaultValues []any   `json:"default_values,omitempty"`
	Disabled      *bool   `json:"disabled,omitempty"`
	MaxValues     *int64  `json:"max_values,omitempty"`
	MinValues     *int64  `json:"min_values,omitempty"`
	Placeholder   *string `json:"placeholder,omitempty"`
	Required      *bool   `json:"required,omitempty"`
	Type          int32   `json:"type"`
}

// ChannelSelectDefaultValue
type ChannelSelectDefaultValue struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}

// ChannelTypes
type ChannelTypes int

const (
	ChannelTypes1  ChannelTypes = 1
	ChannelTypes3  ChannelTypes = 3
	ChannelTypes0  ChannelTypes = 0
	ChannelTypes2  ChannelTypes = 2
	ChannelTypes4  ChannelTypes = 4
	ChannelTypes5  ChannelTypes = 5
	ChannelTypes10 ChannelTypes = 10
	ChannelTypes11 ChannelTypes = 11
	ChannelTypes12 ChannelTypes = 12
	ChannelTypes13 ChannelTypes = 13
	ChannelTypes14 ChannelTypes = 14
	ChannelTypes15 ChannelTypes = 15
)
