// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// CommandPermission
type CommandPermission struct {
	ID         string `json:"id"`
	Permission bool   `json:"permission"`
	Type       int32  `json:"type"`
}

// CommandPermissions
type CommandPermissions struct {
	ID            string `json:"id"`
	ApplicationID string `json:"application_id"`
	GuildID       string `json:"guild_id"`
	Permissions   []any  `json:"permissions"`
}
