// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// ComponentEmoji
type ComponentEmoji struct {
	ID       string `json:"id,omitempty"`
	Animated bool   `json:"animated,omitempty"`
	Name     string `json:"name"`
}

// ComponentEmojiForOptions
type ComponentEmojiForOptions struct {
	ID   any    `json:"id,omitempty"`
	Name string `json:"name"`
}
