// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// ConnectedAccount
type ConnectedAccount struct {
	ID           string  `json:"id"`
	FriendSync   bool    `json:"friend_sync"`
	Integrations []any   `json:"integrations,omitempty"`
	Name         *string `json:"name,omitempty"`
	Revoked      bool    `json:"revoked,omitempty"`
	ShowActivity bool    `json:"show_activity"`
	TwoWayLink   bool    `json:"two_way_link"`
	Type         string  `json:"type"`
	Verified     bool    `json:"verified"`
	Visibility   int32   `json:"visibility"`
}

// ConnectedAccountGuild
type ConnectedAccountGuild struct {
	ID   string  `json:"id"`
	Icon *string `json:"icon,omitempty"`
	Name string  `json:"name"`
}

// ConnectedAccountIntegration
type ConnectedAccountIntegration struct {
	ID      string `json:"id"`
	Account any    `json:"account"`
	Guild   any    `json:"guild"`
	Type    string `json:"type"`
}

// ConnectedAccountProviders
type ConnectedAccountProviders string

const (
	ConnectedAccountProvidersBattlenet       ConnectedAccountProviders = "battlenet"
	ConnectedAccountProvidersBluesky         ConnectedAccountProviders = "bluesky"
	ConnectedAccountProvidersBungie          ConnectedAccountProviders = "bungie"
	ConnectedAccountProvidersEbay            ConnectedAccountProviders = "ebay"
	ConnectedAccountProvidersEpicgames       ConnectedAccountProviders = "epicgames"
	ConnectedAccountProvidersFacebook        ConnectedAccountProviders = "facebook"
	ConnectedAccountProvidersGithub          ConnectedAccountProviders = "github"
	ConnectedAccountProvidersInstagram       ConnectedAccountProviders = "instagram"
	ConnectedAccountProvidersMastodon        ConnectedAccountProviders = "mastodon"
	ConnectedAccountProvidersLeagueoflegends ConnectedAccountProviders = "leagueoflegends"
	ConnectedAccountProvidersPaypal          ConnectedAccountProviders = "paypal"
	ConnectedAccountProvidersPlaystation     ConnectedAccountProviders = "playstation"
	ConnectedAccountProvidersReddit          ConnectedAccountProviders = "reddit"
	ConnectedAccountProvidersRiotgames       ConnectedAccountProviders = "riotgames"
	ConnectedAccountProvidersRoblox          ConnectedAccountProviders = "roblox"
	ConnectedAccountProvidersSkype           ConnectedAccountProviders = "skype"
	ConnectedAccountProvidersSpotify         ConnectedAccountProviders = "spotify"
	ConnectedAccountProvidersSteam           ConnectedAccountProviders = "steam"
	ConnectedAccountProvidersTiktok          ConnectedAccountProviders = "tiktok"
	ConnectedAccountProvidersTwitch          ConnectedAccountProviders = "twitch"
	ConnectedAccountProvidersTwitter         ConnectedAccountProviders = "twitter"
	ConnectedAccountProvidersXbox            ConnectedAccountProviders = "xbox"
	ConnectedAccountProvidersYoutube         ConnectedAccountProviders = "youtube"
	ConnectedAccountProvidersDomain          ConnectedAccountProviders = "domain"
)

// ConnectedAccountVisibility
type ConnectedAccountVisibility int

const (
	ConnectedAccountVisibility0 ConnectedAccountVisibility = 0
	ConnectedAccountVisibility1 ConnectedAccountVisibility = 1
)
