// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// ContainerComponent
type ContainerComponent struct {
	ID          int32  `json:"id"`
	AccentColor *int32 `json:"accent_color,omitempty"`
	Components  []any  `json:"components"`
	Spoiler     bool   `json:"spoiler"`
	Type        int32  `json:"type"`
}

// ContainerComponentForMessageOptions
type ContainerComponentForMessageOptions struct {
	ID          *int32 `json:"id,omitempty"`
	AccentColor *int64 `json:"accent_color,omitempty"`
	Components  []any  `json:"components"`
	Spoiler     *bool  `json:"spoiler,omitempty"`
	Type        int32  `json:"type"`
}
