// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// CreatedThread
type CreatedThread struct {
	ID               string     `json:"id"`
	AppliedTags      []string   `json:"applied_tags,omitempty"`
	Bitrate          int32      `json:"bitrate,omitempty"`
	Flags            int32      `json:"flags"`
	GuildID          string     `json:"guild_id"`
	LastMessageID    any        `json:"last_message_id,omitempty"`
	LastPinTimestamp *time.Time `json:"last_pin_timestamp,omitempty"`
	Member           any        `json:"member,omitempty"`
	MemberCount      int32      `json:"member_count"`
	MessageCount     int32      `json:"message_count"`
	Name             string     `json:"name"`
	OwnerID          string     `json:"owner_id"`
	ParentID         any        `json:"parent_id,omitempty"`
	Permissions      *string    `json:"permissions,omitempty"`
	RateLimitPerUser int32      `json:"rate_limit_per_user,omitempty"`
	RtcRegion        *string    `json:"rtc_region,omitempty"`
	ThreadMetadata   any        `json:"thread_metadata"`
	TotalMessageSent int32      `json:"total_message_sent"`
	Type             int32      `json:"type"`
	UserLimit        int32      `json:"user_limit,omitempty"`
	VideoQualityMode int32      `json:"video_quality_mode,omitempty"`
}
