// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// CreateEntitlementOptionsData
type CreateEntitlementOptionsData struct {
	OwnerID   string `json:"owner_id"`
	OwnerType int32  `json:"owner_type"`
	SkuID     string `json:"sku_id"`
}

// CreateForumThreadOptions
type CreateForumThreadOptions struct {
	AppliedTags         []string `json:"applied_tags,omitempty"`
	AutoArchiveDuration any      `json:"auto_archive_duration,omitempty"`
	Message             any      `json:"message"`
	Name                string   `json:"name"`
	RateLimitPerUser    *int64   `json:"rate_limit_per_user,omitempty"`
}

// CreateGroupDMInviteOptions
type CreateGroupDMInviteOptions struct {
	MaxAge *int64 `json:"max_age,omitempty"`
}

// CreateGuildChannelOptions
type CreateGuildChannelOptions struct {
	AvailableTags                 []any   `json:"available_tags,omitempty"`
	Bitrate                       *int32  `json:"bitrate,omitempty"`
	DefaultAutoArchiveDuration    any     `json:"default_auto_archive_duration,omitempty"`
	DefaultForumLayout            any     `json:"default_forum_layout,omitempty"`
	DefaultReactionEmoji          any     `json:"default_reaction_emoji,omitempty"`
	DefaultSortOrder              any     `json:"default_sort_order,omitempty"`
	DefaultTagSetting             any     `json:"default_tag_setting,omitempty"`
	DefaultThreadRateLimitPerUser *int64  `json:"default_thread_rate_limit_per_user,omitempty"`
	Name                          string  `json:"name"`
	Nsfw                          *bool   `json:"nsfw,omitempty"`
	ParentID                      any     `json:"parent_id,omitempty"`
	PermissionOverwrites          []any   `json:"permission_overwrites,omitempty"`
	Position                      *int32  `json:"position,omitempty"`
	RateLimitPerUser              *int64  `json:"rate_limit_per_user,omitempty"`
	RtcRegion                     *string `json:"rtc_region,omitempty"`
	Topic                         *string `json:"topic,omitempty"`
	Type                          any     `json:"type,omitempty"`
	UserLimit                     *int32  `json:"user_limit,omitempty"`
	VideoQualityMode              any     `json:"video_quality_mode,omitempty"`
}

// CreateGuildInviteOptions
type CreateGuildInviteOptions struct {
	MaxAge              *int64 `json:"max_age,omitempty"`
	MaxUses             *int64 `json:"max_uses,omitempty"`
	TargetApplicationID any    `json:"target_application_id,omitempty"`
	TargetType          any    `json:"target_type,omitempty"`
	TargetUserID        any    `json:"target_user_id,omitempty"`
	Temporary           *bool  `json:"temporary,omitempty"`
	Unique              *bool  `json:"unique,omitempty"`
}

// CreateMessageInteractionCallback
type CreateMessageInteractionCallback struct {
	Message any   `json:"message"`
	Type    int32 `json:"type"`
}

// CreateMessageInteractionCallbackOptions
type CreateMessageInteractionCallbackOptions struct {
	Data any   `json:"data,omitempty"`
	Type int32 `json:"type"`
}

// CreateOrUpdateThreadTagOptions
type CreateOrUpdateThreadTagOptions struct {
	EmojiID   any     `json:"emoji_id,omitempty"`
	EmojiName *string `json:"emoji_name,omitempty"`
	Moderated *bool   `json:"moderated,omitempty"`
	Name      string  `json:"name"`
}

// CreatePrivateChannelOptions
type CreatePrivateChannelOptions struct {
	AccessTokens []string           `json:"access_tokens,omitempty"`
	Nicks        map[string]*string `json:"nicks,omitempty"`
	RecipientID  any                `json:"recipient_id,omitempty"`
}

// CreateRoleOptions
type CreateRoleOptions struct {
	Color        *int64  `json:"color,omitempty"`
	Hoist        *bool   `json:"hoist,omitempty"`
	Icon         *string `json:"icon,omitempty"`
	Mentionable  *bool   `json:"mentionable,omitempty"`
	Name         *string `json:"name,omitempty"`
	Permissions  *int64  `json:"permissions,omitempty"`
	UnicodeEmoji *string `json:"unicode_emoji,omitempty"`
}

// CreateTextThreadWithMessageOptions
type CreateTextThreadWithMessageOptions struct {
	AutoArchiveDuration any    `json:"auto_archive_duration,omitempty"`
	Name                string `json:"name"`
	RateLimitPerUser    *int64 `json:"rate_limit_per_user,omitempty"`
}

// CreateTextThreadWithoutMessageOptions
type CreateTextThreadWithoutMessageOptions struct {
	AutoArchiveDuration any    `json:"auto_archive_duration,omitempty"`
	Invitable           *bool  `json:"invitable,omitempty"`
	Name                string `json:"name"`
	RateLimitPerUser    *int64 `json:"rate_limit_per_user,omitempty"`
	Type                any    `json:"type,omitempty"`
}
