// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// CustomClientTheme
type CustomClientTheme struct {
	BaseMix       int32    `json:"base_mix"`
	BaseTheme     int32    `json:"base_theme"`
	Colors        []string `json:"colors"`
	GradientAngle int32    `json:"gradient_angle"`
}

// CustomClientThemeShareOptions
type CustomClientThemeShareOptions struct {
	BaseMix       int32    `json:"base_mix"`
	BaseTheme     any      `json:"base_theme,omitempty"`
	Colors        []string `json:"colors"`
	GradientAngle int32    `json:"gradient_angle"`
}
