// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// DefaultKeywordListTriggerMetadata
type DefaultKeywordListTriggerMetadata struct {
	AllowList []string `json:"allow_list,omitempty"`
	Presets   []int32  `json:"presets,omitempty"`
}

// DefaultKeywordListUpsertOptions
type DefaultKeywordListUpsertOptions struct {
	Actions         []any    `json:"actions,omitempty"`
	Enabled         *bool    `json:"enabled,omitempty"`
	EventType       int32    `json:"event_type"`
	ExemptChannels  []string `json:"exempt_channels,omitempty"`
	ExemptRoles     []string `json:"exempt_roles,omitempty"`
	Name            string   `json:"name"`
	TriggerMetadata any      `json:"trigger_metadata"`
	TriggerType     int32    `json:"trigger_type"`
}

// DefaultKeywordListUpsertOptionsPartial
type DefaultKeywordListUpsertOptionsPartial struct {
	Actions         []any    `json:"actions,omitempty"`
	Enabled         *bool    `json:"enabled,omitempty"`
	EventType       int32    `json:"event_type,omitempty"`
	ExemptChannels  []string `json:"exempt_channels,omitempty"`
	ExemptRoles     []string `json:"exempt_roles,omitempty"`
	Name            string   `json:"name,omitempty"`
	TriggerMetadata any      `json:"trigger_metadata,omitempty"`
	TriggerType     int32    `json:"trigger_type,omitempty"`
}

// DefaultKeywordRule
type DefaultKeywordRule struct {
	ID              string   `json:"id"`
	Actions         []any    `json:"actions"`
	CreatorID       string   `json:"creator_id"`
	Enabled         bool     `json:"enabled"`
	EventType       int32    `json:"event_type"`
	ExemptChannels  []string `json:"exempt_channels"`
	ExemptRoles     []string `json:"exempt_roles"`
	GuildID         string   `json:"guild_id"`
	Name            string   `json:"name"`
	TriggerMetadata any      `json:"trigger_metadata"`
	TriggerType     int32    `json:"trigger_type"`
}

// DefaultReactionEmoji
type DefaultReactionEmoji struct {
	EmojiID   any     `json:"emoji_id,omitempty"`
	EmojiName *string `json:"emoji_name,omitempty"`
}
