// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// DiscordIntegration
type DiscordIntegration struct {
	ID          string   `json:"id"`
	Account     any      `json:"account"`
	Application any      `json:"application"`
	Enabled     bool     `json:"enabled"`
	Name        *string  `json:"name,omitempty"`
	Scopes      []string `json:"scopes"`
	Type        string   `json:"type"`
	User        any      `json:"user,omitempty"`
}
