// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// EmbeddedActivityInstance
type EmbeddedActivityInstance struct {
	ApplicationID string   `json:"application_id"`
	InstanceID    string   `json:"instance_id"`
	LaunchID      string   `json:"launch_id"`
	Location      any      `json:"location"`
	Users         []string `json:"users"`
}

// EmbeddedActivityLocationKind
type EmbeddedActivityLocationKind string

const (
	EmbeddedActivityLocationKindGc    EmbeddedActivityLocationKind = "gc"
	EmbeddedActivityLocationKindPc    EmbeddedActivityLocationKind = "pc"
	EmbeddedActivityLocationKindParty EmbeddedActivityLocationKind = "party"
)
