// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// Emoji
type Emoji struct {
	ID            string   `json:"id"`
	Animated      bool     `json:"animated"`
	Available     bool     `json:"available"`
	Managed       bool     `json:"managed"`
	Name          string   `json:"name"`
	RequireColons bool     `json:"require_colons"`
	Roles         []string `json:"roles"`
	User          any      `json:"user,omitempty"`
}
