// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// EntityMetadataExternal
type EntityMetadataExternal struct {
	Location string `json:"location"`
}

// EntityMetadataStageInstance
type EntityMetadataStageInstance struct {
}

// EntityMetadataVoice
type EntityMetadataVoice struct {
}
