// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// Entitlement
type Entitlement struct {
	ID                string     `json:"id"`
	ApplicationID     string     `json:"application_id"`
	Consumed          *bool      `json:"consumed,omitempty"`
	Deleted           bool       `json:"deleted"`
	EndsAt            *time.Time `json:"ends_at,omitempty"`
	FulfilledAt       *time.Time `json:"fulfilled_at,omitempty"`
	FulfillmentStatus any        `json:"fulfillment_status,omitempty"`
	GifterUserID      any        `json:"gifter_user_id,omitempty"`
	GuildID           any        `json:"guild_id,omitempty"`
	ParentID          any        `json:"parent_id,omitempty"`
	SkuID             string     `json:"sku_id"`
	StartsAt          *time.Time `json:"starts_at,omitempty"`
	Type              int32      `json:"type"`
	UserID            string     `json:"user_id"`
}

// EntitlementOwnerTypes
type EntitlementOwnerTypes struct {
}

// EntitlementTenantFulfillmentStatus
type EntitlementTenantFulfillmentStatus int

const (
	EntitlementTenantFulfillmentStatus0 EntitlementTenantFulfillmentStatus = 0
	EntitlementTenantFulfillmentStatus1 EntitlementTenantFulfillmentStatus = 1
	EntitlementTenantFulfillmentStatus2 EntitlementTenantFulfillmentStatus = 2
	EntitlementTenantFulfillmentStatus3 EntitlementTenantFulfillmentStatus = 3
	EntitlementTenantFulfillmentStatus4 EntitlementTenantFulfillmentStatus = 4
	EntitlementTenantFulfillmentStatus5 EntitlementTenantFulfillmentStatus = 5
	EntitlementTenantFulfillmentStatus6 EntitlementTenantFulfillmentStatus = 6
	EntitlementTenantFulfillmentStatus7 EntitlementTenantFulfillmentStatus = 7
)

// EntitlementTypes
type EntitlementTypes int

const (
	EntitlementTypes8  EntitlementTypes = 8
	EntitlementTypes10 EntitlementTypes = 10
)
