// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// Error A single error, either for an API response or a specific field.
type ErrorResponse struct {
	Code    int64  `json:"code"`    // Discord internal error code. See error code reference
	Message string `json:"message"` // Human-readable error message
}

// ErrorDetails
type ErrorDetails struct {
}
