// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// ExternalConnectionIntegration
type ExternalConnectionIntegration struct {
	ID                string    `json:"id"`
	Account           any       `json:"account"`
	EnableEmoticons   bool      `json:"enable_emoticons,omitempty"`
	Enabled           bool      `json:"enabled"`
	ExpireBehavior    int32     `json:"expire_behavior,omitempty"`
	ExpireGracePeriod int32     `json:"expire_grace_period,omitempty"`
	Name              *string   `json:"name,omitempty"`
	Revoked           bool      `json:"revoked,omitempty"`
	RoleID            any       `json:"role_id,omitempty"`
	SubscriberCount   int32     `json:"subscriber_count,omitempty"`
	SyncedAt          time.Time `json:"synced_at,omitempty"`
	Syncing           bool      `json:"syncing,omitempty"`
	Type              string    `json:"type"`
	User              any       `json:"user"`
}

// ExternalScheduledEvent
type ExternalScheduledEvent struct {
	ID                 string     `json:"id"`
	ChannelID          any        `json:"channel_id,omitempty"`
	Creator            any        `json:"creator,omitempty"`
	CreatorID          any        `json:"creator_id,omitempty"`
	Description        *string    `json:"description,omitempty"`
	EntityID           any        `json:"entity_id,omitempty"`
	EntityMetadata     any        `json:"entity_metadata"`
	EntityType         int32      `json:"entity_type"`
	GuildID            string     `json:"guild_id"`
	Image              *string    `json:"image,omitempty"`
	Name               string     `json:"name"`
	PrivacyLevel       int32      `json:"privacy_level"`
	ScheduledEndTime   *time.Time `json:"scheduled_end_time,omitempty"`
	ScheduledStartTime time.Time  `json:"scheduled_start_time"`
	Status             int32      `json:"status"`
	UserCount          int32      `json:"user_count,omitempty"`
	UserRsvp           any        `json:"user_rsvp,omitempty"`
}

// ExternalScheduledEventCreateOptions
type ExternalScheduledEventCreateOptions struct {
	ChannelID          any        `json:"channel_id,omitempty"`
	Description        *string    `json:"description,omitempty"`
	EntityMetadata     any        `json:"entity_metadata"`
	EntityType         int32      `json:"entity_type"`
	Image              *string    `json:"image,omitempty"`
	Name               string     `json:"name"`
	PrivacyLevel       int32      `json:"privacy_level"`
	ScheduledEndTime   *time.Time `json:"scheduled_end_time,omitempty"`
	ScheduledStartTime time.Time  `json:"scheduled_start_time"`
}

// ExternalScheduledEventPatchOptionsPartial
type ExternalScheduledEventPatchOptionsPartial struct {
	ChannelID          any        `json:"channel_id,omitempty"`
	Description        *string    `json:"description,omitempty"`
	EntityMetadata     any        `json:"entity_metadata,omitempty"`
	EntityType         any        `json:"entity_type,omitempty"`
	Image              *string    `json:"image,omitempty"`
	Name               string     `json:"name,omitempty"`
	PrivacyLevel       int32      `json:"privacy_level,omitempty"`
	ScheduledEndTime   *time.Time `json:"scheduled_end_time,omitempty"`
	ScheduledStartTime time.Time  `json:"scheduled_start_time,omitempty"`
	Status             any        `json:"status,omitempty"`
}
