// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// FileComponent
type FileComponent struct {
	ID      int32   `json:"id"`
	File    any     `json:"file"`
	Name    *string `json:"name,omitempty"`
	Size    *int32  `json:"size,omitempty"`
	Spoiler bool    `json:"spoiler"`
	Type    int32   `json:"type"`
}

// FileComponentForMessageOptions
type FileComponentForMessageOptions struct {
	ID      *int32 `json:"id,omitempty"`
	File    any    `json:"file"`
	Spoiler *bool  `json:"spoiler,omitempty"`
	Type    int32  `json:"type"`
}

// FileUploadComponentForModalOptions
type FileUploadComponentForModalOptions struct {
	ID        *int32 `json:"id,omitempty"`
	CustomID  string `json:"custom_id"`
	MaxValues *int64 `json:"max_values,omitempty"`
	MinValues *int64 `json:"min_values,omitempty"`
	Required  *bool  `json:"required,omitempty"`
	Type      int32  `json:"type"`
}
