// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// FlagToChannelAction
type FlagToChannelAction struct {
	Metadata any   `json:"metadata"`
	Type     int32 `json:"type"`
}

// FlagToChannelActionMetadata
type FlagToChannelActionMetadata struct {
	ChannelID string `json:"channel_id"`
}
