// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// ForumLayout
type ForumLayout int

const (
	ForumLayout0 ForumLayout = 0
	ForumLayout1 ForumLayout = 1
	ForumLayout2 ForumLayout = 2
)

// ForumTag
type ForumTag struct {
	ID        string  `json:"id"`
	EmojiID   any     `json:"emoji_id,omitempty"`
	EmojiName *string `json:"emoji_name,omitempty"`
	Moderated bool    `json:"moderated"`
	Name      string  `json:"name"`
}
