// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// FriendInvite
type FriendInvite struct {
	Channel      any        `json:"channel,omitempty"`
	Code         string     `json:"code"`
	CreatedAt    time.Time  `json:"created_at,omitempty"`
	ExpiresAt    *time.Time `json:"expires_at,omitempty"`
	Flags        int32      `json:"flags,omitempty"`
	FriendsCount int32      `json:"friends_count,omitempty"`
	Inviter      any        `json:"inviter,omitempty"`
	IsContact    bool       `json:"is_contact,omitempty"`
	MaxAge       int32      `json:"max_age,omitempty"`
	MaxUses      int32      `json:"max_uses,omitempty"`
	Type         int32      `json:"type"`
	Uses         int32      `json:"uses,omitempty"`
}
