// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// Gateway
type Gateway struct {
	URL string `json:"url"`
}

// GatewayBot
type GatewayBot struct {
	SessionStartLimit any    `json:"session_start_limit"`
	Shards            int32  `json:"shards"`
	URL               string `json:"url"`
}

// GatewayBotSessionStartLimit
type GatewayBotSessionStartLimit struct {
	MaxConcurrency int32 `json:"max_concurrency"`
	Remaining      int32 `json:"remaining"`
	ResetAfter     int32 `json:"reset_after"`
	Total          int32 `json:"total"`
}
