// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// GithubAuthor
type GithubAuthor struct {
	Name     string  `json:"name"`
	Username *string `json:"username,omitempty"`
}

// GithubCheckApp
type GithubCheckApp struct {
	Name string `json:"name"`
}

// GithubCheckPullOptions
type GithubCheckPullOptions struct {
	Number int64 `json:"number"`
}

// GithubCheckRun
type GithubCheckRun struct {
	CheckSuite   any     `json:"check_suite"`
	Conclusion   *string `json:"conclusion,omitempty"`
	DetailsURL   *string `json:"details_url,omitempty"`
	HTMLURL      string  `json:"html_url"`
	Name         string  `json:"name"`
	Output       any     `json:"output,omitempty"`
	PullRequests []any   `json:"pull_requests,omitempty"`
}

// GithubCheckRunOutput
type GithubCheckRunOutput struct {
	Summary *string `json:"summary,omitempty"`
	Title   *string `json:"title,omitempty"`
}

// GithubCheckSuite
type GithubCheckSuite struct {
	App          any     `json:"app"`
	Conclusion   *string `json:"conclusion,omitempty"`
	HeadBranch   *string `json:"head_branch,omitempty"`
	HeadSha      string  `json:"head_sha"`
	PullRequests []any   `json:"pull_requests,omitempty"`
}

// GithubComment
type GithubComment struct {
	ID       int64   `json:"id"`
	Body     string  `json:"body"`
	CommitID *string `json:"commit_id,omitempty"`
	HTMLURL  string  `json:"html_url"`
	User     any     `json:"user"`
}

// GithubCommit
type GithubCommit struct {
	ID      string `json:"id"`
	Author  any    `json:"author"`
	Message string `json:"message"`
	URL     string `json:"url"`
}

// GithubDiscussion
type GithubDiscussion struct {
	AnswerHTMLURL *string `json:"answer_html_url,omitempty"`
	Body          *string `json:"body,omitempty"`
	HTMLURL       string  `json:"html_url"`
	Number        int64   `json:"number"`
	Title         string  `json:"title"`
	User          any     `json:"user"`
}

// GithubIssue
type GithubIssue struct {
	ID          int64   `json:"id"`
	Body        *string `json:"body,omitempty"`
	HTMLURL     string  `json:"html_url"`
	Number      int64   `json:"number"`
	PullRequest any     `json:"pull_request,omitempty"`
	Title       string  `json:"title"`
	User        any     `json:"user"`
}

// GithubRelease
type GithubRelease struct {
	ID      int64  `json:"id"`
	Author  any    `json:"author"`
	HTMLURL string `json:"html_url"`
	TagName string `json:"tag_name"`
}

// GithubRepository
type GithubRepository struct {
	ID       int64  `json:"id"`
	FullName string `json:"full_name"`
	HTMLURL  string `json:"html_url"`
	Name     string `json:"name"`
}

// GithubReview
type GithubReview struct {
	Body    *string `json:"body,omitempty"`
	HTMLURL string  `json:"html_url"`
	State   string  `json:"state"`
	User    any     `json:"user"`
}

// GithubUser
type GithubUser struct {
	ID        int64  `json:"id"`
	AvatarURL string `json:"avatar_url"`
	HTMLURL   string `json:"html_url"`
	Login     string `json:"login"`
}

// GithubWebhook
type GithubWebhook struct {
	Action      *string `json:"action,omitempty"`
	Answer      any     `json:"answer,omitempty"`
	CheckRun    any     `json:"check_run,omitempty"`
	CheckSuite  any     `json:"check_suite,omitempty"`
	Comment     any     `json:"comment,omitempty"`
	Commits     []any   `json:"commits,omitempty"`
	Compare     *string `json:"compare,omitempty"`
	Discussion  any     `json:"discussion,omitempty"`
	Forced      *bool   `json:"forced,omitempty"`
	Forkee      any     `json:"forkee,omitempty"`
	HeadCommit  any     `json:"head_commit,omitempty"`
	Issue       any     `json:"issue,omitempty"`
	Member      any     `json:"member,omitempty"`
	PullRequest any     `json:"pull_request,omitempty"`
	Ref         *string `json:"ref,omitempty"`
	RefType     *string `json:"ref_type,omitempty"`
	Release     any     `json:"release,omitempty"`
	Repository  any     `json:"repository,omitempty"`
	Review      any     `json:"review,omitempty"`
	Sender      any     `json:"sender"`
}
