// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// GroupDMInvite
type GroupDMInvite struct {
	ApproximateMemberCount *int32     `json:"approximate_member_count,omitempty"`
	Channel                any        `json:"channel"`
	Code                   string     `json:"code"`
	CreatedAt              time.Time  `json:"created_at,omitempty"`
	ExpiresAt              *time.Time `json:"expires_at,omitempty"`
	Inviter                any        `json:"inviter,omitempty"`
	MaxAge                 int32      `json:"max_age,omitempty"`
	Type                   int32      `json:"type"`
}
