// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// Guild
type Guild struct {
	ID                          string   `json:"id"`
	AfkChannelID                any      `json:"afk_channel_id,omitempty"`
	AfkTimeout                  int32    `json:"afk_timeout"`
	ApplicationID               any      `json:"application_id,omitempty"`
	Banner                      *string  `json:"banner,omitempty"`
	DefaultMessageNotifications int32    `json:"default_message_notifications"`
	Description                 *string  `json:"description,omitempty"`
	DiscoverySplash             *string  `json:"discovery_splash,omitempty"`
	Emojis                      []any    `json:"emojis"`
	ExplicitContentFilter       int32    `json:"explicit_content_filter"`
	Features                    []string `json:"features"`
	HomeHeader                  *string  `json:"home_header,omitempty"`
	Icon                        *string  `json:"icon,omitempty"`
	MaxMembers                  int32    `json:"max_members"`
	MaxPresences                *int32   `json:"max_presences,omitempty"`
	MaxStageVideoChannelUsers   int32    `json:"max_stage_video_channel_users"`
	MaxVideoChannelUsers        int32    `json:"max_video_channel_users"`
	MfaLevel                    int32    `json:"mfa_level"`
	Name                        string   `json:"name"`
	Nsfw                        bool     `json:"nsfw"`
	NsfwLevel                   int32    `json:"nsfw_level"`
	OwnerID                     string   `json:"owner_id"`
	PreferredLocale             string   `json:"preferred_locale"`
	PremiumProgressBarEnabled   bool     `json:"premium_progress_bar_enabled"`
	PremiumSubscriptionCount    int32    `json:"premium_subscription_count"`
	PremiumTier                 int32    `json:"premium_tier"`
	PublicUpdatesChannelID      any      `json:"public_updates_channel_id,omitempty"`
	Region                      string   `json:"region"`
	Roles                       []any    `json:"roles"`
	RulesChannelID              any      `json:"rules_channel_id,omitempty"`
	SafetyAlertsChannelID       any      `json:"safety_alerts_channel_id,omitempty"`
	Splash                      *string  `json:"splash,omitempty"`
	Stickers                    []any    `json:"stickers"`
	SystemChannelFlags          int32    `json:"system_channel_flags"`
	SystemChannelID             any      `json:"system_channel_id,omitempty"`
	VanityURLCode               *string  `json:"vanity_url_code,omitempty"`
	VerificationLevel           int32    `json:"verification_level"`
	WidgetChannelID             any      `json:"widget_channel_id,omitempty"`
	WidgetEnabled               bool     `json:"widget_enabled"`
}

// GuildAuditLog
type GuildAuditLog struct {
	ApplicationCommands  []any `json:"application_commands"`
	AuditLogEntries      []any `json:"audit_log_entries"`
	AutoModerationRules  []any `json:"auto_moderation_rules"`
	GuildScheduledEvents []any `json:"guild_scheduled_events"`
	Integrations         []any `json:"integrations"`
	Threads              []any `json:"threads"`
	Users                []any `json:"users"`
	Webhooks             []any `json:"webhooks"`
}

// GuildBan
type GuildBan struct {
	Reason *string `json:"reason,omitempty"`
	User   any     `json:"user"`
}

// GuildChannel
type GuildChannel struct {
	ID                            string     `json:"id"`
	AvailableTags                 []any      `json:"available_tags,omitempty"`
	Bitrate                       int32      `json:"bitrate,omitempty"`
	DefaultAutoArchiveDuration    int32      `json:"default_auto_archive_duration,omitempty"`
	DefaultForumLayout            any        `json:"default_forum_layout,omitempty"`
	DefaultReactionEmoji          any        `json:"default_reaction_emoji,omitempty"`
	DefaultSortOrder              any        `json:"default_sort_order,omitempty"`
	DefaultTagSetting             any        `json:"default_tag_setting,omitempty"`
	DefaultThreadRateLimitPerUser int32      `json:"default_thread_rate_limit_per_user,omitempty"`
	Flags                         int32      `json:"flags"`
	GuildID                       string     `json:"guild_id"`
	HdStreamingBuyerID            string     `json:"hd_streaming_buyer_id,omitempty"`
	HdStreamingUntil              time.Time  `json:"hd_streaming_until,omitempty"`
	LastMessageID                 any        `json:"last_message_id,omitempty"`
	LastPinTimestamp              *time.Time `json:"last_pin_timestamp,omitempty"`
	Name                          string     `json:"name"`
	Nsfw                          bool       `json:"nsfw,omitempty"`
	ParentID                      any        `json:"parent_id,omitempty"`
	PermissionOverwrites          []any      `json:"permission_overwrites,omitempty"`
	Permissions                   *string    `json:"permissions,omitempty"`
	Position                      int32      `json:"position"`
	RateLimitPerUser              int32      `json:"rate_limit_per_user,omitempty"`
	RtcRegion                     *string    `json:"rtc_region,omitempty"`
	Topic                         *string    `json:"topic,omitempty"`
	Type                          int32      `json:"type"`
	UserLimit                     int32      `json:"user_limit,omitempty"`
	VideoQualityMode              int32      `json:"video_quality_mode,omitempty"`
}

// GuildChannelLocation
type GuildChannelLocation struct {
	ID        string `json:"id"`
	ChannelID string `json:"channel_id"`
	GuildID   string `json:"guild_id"`
	Kind      string `json:"kind"`
}

// GuildExplicitContentFilterTypes
type GuildExplicitContentFilterTypes int

const (
	GuildExplicitContentFilterTypes0 GuildExplicitContentFilterTypes = 0
	GuildExplicitContentFilterTypes1 GuildExplicitContentFilterTypes = 1
	GuildExplicitContentFilterTypes2 GuildExplicitContentFilterTypes = 2
)

// GuildFeatures
type GuildFeatures string

const (
	GuildFeaturesANIMATEDBANNER                        GuildFeatures = "ANIMATED_BANNER"
	GuildFeaturesANIMATEDICON                          GuildFeatures = "ANIMATED_ICON"
	GuildFeaturesAPPLICATIONCOMMANDPERMISSIONSV2       GuildFeatures = "APPLICATION_COMMAND_PERMISSIONS_V2"
	GuildFeaturesAUTOMODERATION                        GuildFeatures = "AUTO_MODERATION"
	GuildFeaturesBANNER                                GuildFeatures = "BANNER"
	GuildFeaturesCOMMUNITY                             GuildFeatures = "COMMUNITY"
	GuildFeaturesCREATORMONETIZABLEPROVISIONAL         GuildFeatures = "CREATOR_MONETIZABLE_PROVISIONAL"
	GuildFeaturesCREATORSTOREPAGE                      GuildFeatures = "CREATOR_STORE_PAGE"
	GuildFeaturesDEVELOPERSUPPORTSERVER                GuildFeatures = "DEVELOPER_SUPPORT_SERVER"
	GuildFeaturesDISCOVERABLE                          GuildFeatures = "DISCOVERABLE"
	GuildFeaturesFEATURABLE                            GuildFeatures = "FEATURABLE"
	GuildFeaturesINVITESDISABLED                       GuildFeatures = "INVITES_DISABLED"
	GuildFeaturesINVITESPLASH                          GuildFeatures = "INVITE_SPLASH"
	GuildFeaturesMEMBERVERIFICATIONGATEENABLED         GuildFeatures = "MEMBER_VERIFICATION_GATE_ENABLED"
	GuildFeaturesMORESTICKERS                          GuildFeatures = "MORE_STICKERS"
	GuildFeaturesNEWS                                  GuildFeatures = "NEWS"
	GuildFeaturesPARTNERED                             GuildFeatures = "PARTNERED"
	GuildFeaturesPREVIEWENABLED                        GuildFeatures = "PREVIEW_ENABLED"
	GuildFeaturesRAIDALERTSDISABLED                    GuildFeatures = "RAID_ALERTS_DISABLED"
	GuildFeaturesROLEICONS                             GuildFeatures = "ROLE_ICONS"
	GuildFeaturesROLESUBSCRIPTIONSAVAILABLEFORPURCHASE GuildFeatures = "ROLE_SUBSCRIPTIONS_AVAILABLE_FOR_PURCHASE"
	GuildFeaturesROLESUBSCRIPTIONSENABLED              GuildFeatures = "ROLE_SUBSCRIPTIONS_ENABLED"
	GuildFeaturesTICKETEDEVENTSENABLED                 GuildFeatures = "TICKETED_EVENTS_ENABLED"
	GuildFeaturesVANITYURL                             GuildFeatures = "VANITY_URL"
	GuildFeaturesVERIFIED                              GuildFeatures = "VERIFIED"
	GuildFeaturesVIPREGIONS                            GuildFeatures = "VIP_REGIONS"
	GuildFeaturesWELCOMESCREENENABLED                  GuildFeatures = "WELCOME_SCREEN_ENABLED"
)

// GuildHomeSettings
type GuildHomeSettings struct {
	Enabled          bool   `json:"enabled"`
	GuildID          string `json:"guild_id"`
	NewMemberActions []any  `json:"new_member_actions"`
	ResourceChannels []any  `json:"resource_channels"`
	WelcomeMessage   any    `json:"welcome_message,omitempty"`
}

// GuildIncomingWebhook
type GuildIncomingWebhook struct {
	ID            string  `json:"id"`
	ApplicationID any     `json:"application_id,omitempty"`
	Avatar        *string `json:"avatar,omitempty"`
	ChannelID     any     `json:"channel_id,omitempty"`
	GuildID       any     `json:"guild_id,omitempty"`
	Name          string  `json:"name"`
	Token         string  `json:"token,omitempty"`
	Type          int32   `json:"type"`
	URL           string  `json:"url,omitempty"`
	User          any     `json:"user,omitempty"`
}

// GuildInvite
type GuildInvite struct {
	ApproximateMemberCount   *int32     `json:"approximate_member_count,omitempty"`
	ApproximatePresenceCount *int32     `json:"approximate_presence_count,omitempty"`
	Channel                  any        `json:"channel"`
	Code                     string     `json:"code"`
	CreatedAt                time.Time  `json:"created_at,omitempty"`
	ExpiresAt                *time.Time `json:"expires_at,omitempty"`
	Flags                    int32      `json:"flags,omitempty"`
	Guild                    any        `json:"guild"`
	GuildID                  string     `json:"guild_id"`
	GuildScheduledEvent      any        `json:"guild_scheduled_event,omitempty"`
	Inviter                  any        `json:"inviter,omitempty"`
	IsContact                bool       `json:"is_contact,omitempty"`
	IsNicknameChangeable     bool       `json:"is_nickname_changeable,omitempty"`
	MaxAge                   int32      `json:"max_age,omitempty"`
	MaxUses                  int32      `json:"max_uses,omitempty"`
	TargetApplication        any        `json:"target_application,omitempty"`
	TargetType               int32      `json:"target_type,omitempty"`
	TargetUser               any        `json:"target_user,omitempty"`
	Temporary                bool       `json:"temporary,omitempty"`
	Type                     int32      `json:"type"`
	Uses                     int32      `json:"uses,omitempty"`
}

// GuildMFALevel
type GuildMFALevel int

const (
	GuildMFALevel0 GuildMFALevel = 0
	GuildMFALevel1 GuildMFALevel = 1
)

// GuildMember
type GuildMember struct {
	Avatar                     *string    `json:"avatar,omitempty"`
	AvatarDecorationData       any        `json:"avatar_decoration_data,omitempty"`
	Banner                     *string    `json:"banner,omitempty"`
	Collectibles               any        `json:"collectibles,omitempty"`
	CommunicationDisabledUntil *time.Time `json:"communication_disabled_until,omitempty"`
	Deaf                       bool       `json:"deaf"`
	Flags                      int32      `json:"flags"`
	JoinedAt                   time.Time  `json:"joined_at"`
	Mute                       bool       `json:"mute"`
	Nick                       *string    `json:"nick,omitempty"`
	Pending                    bool       `json:"pending"`
	PremiumSince               *time.Time `json:"premium_since,omitempty"`
	Roles                      []string   `json:"roles"`
	User                       any        `json:"user"`
}

// GuildNSFWContentLevel
type GuildNSFWContentLevel int

const (
	GuildNSFWContentLevel0 GuildNSFWContentLevel = 0
	GuildNSFWContentLevel1 GuildNSFWContentLevel = 1
	GuildNSFWContentLevel2 GuildNSFWContentLevel = 2
	GuildNSFWContentLevel3 GuildNSFWContentLevel = 3
)

// GuildOnboarding
type GuildOnboarding struct {
	DefaultChannelIds []string `json:"default_channel_ids"`
	Enabled           bool     `json:"enabled"`
	GuildID           string   `json:"guild_id"`
	Prompts           []any    `json:"prompts"`
}

// GuildOnboardingMode
type GuildOnboardingMode int

const (
	GuildOnboardingMode0 GuildOnboardingMode = 0
	GuildOnboardingMode1 GuildOnboardingMode = 1
)

// GuildPatchOptionsPartial
type GuildPatchOptionsPartial struct {
	AfkChannelID                any       `json:"afk_channel_id,omitempty"`
	AfkTimeout                  any       `json:"afk_timeout,omitempty"`
	Banner                      *string   `json:"banner,omitempty"`
	DefaultMessageNotifications any       `json:"default_message_notifications,omitempty"`
	Description                 *string   `json:"description,omitempty"`
	DiscoverySplash             *string   `json:"discovery_splash,omitempty"`
	ExplicitContentFilter       any       `json:"explicit_content_filter,omitempty"`
	Features                    []*string `json:"features,omitempty"`
	HomeHeader                  *string   `json:"home_header,omitempty"`
	Icon                        *string   `json:"icon,omitempty"`
	Name                        string    `json:"name,omitempty"`
	PreferredLocale             any       `json:"preferred_locale,omitempty"`
	PremiumProgressBarEnabled   *bool     `json:"premium_progress_bar_enabled,omitempty"`
	PublicUpdatesChannelID      any       `json:"public_updates_channel_id,omitempty"`
	Region                      *string   `json:"region,omitempty"`
	RulesChannelID              any       `json:"rules_channel_id,omitempty"`
	SafetyAlertsChannelID       any       `json:"safety_alerts_channel_id,omitempty"`
	Splash                      *string   `json:"splash,omitempty"`
	SystemChannelFlags          *int64    `json:"system_channel_flags,omitempty"`
	SystemChannelID             any       `json:"system_channel_id,omitempty"`
	VerificationLevel           any       `json:"verification_level,omitempty"`
}

// GuildPreview
type GuildPreview struct {
	ID                       string   `json:"id"`
	ApproximateMemberCount   int32    `json:"approximate_member_count"`
	ApproximatePresenceCount int32    `json:"approximate_presence_count"`
	Description              *string  `json:"description,omitempty"`
	DiscoverySplash          *string  `json:"discovery_splash,omitempty"`
	Emojis                   []any    `json:"emojis"`
	Features                 []string `json:"features"`
	HomeHeader               *string  `json:"home_header,omitempty"`
	Icon                     *string  `json:"icon,omitempty"`
	Name                     string   `json:"name"`
	Splash                   *string  `json:"splash,omitempty"`
	Stickers                 []any    `json:"stickers"`
}

// GuildProductPurchase
type GuildProductPurchase struct {
	ListingID   string `json:"listing_id"`
	ProductName string `json:"product_name"`
}

// GuildPrune
type GuildPrune struct {
	Pruned *int32 `json:"pruned,omitempty"`
}

// GuildRole
type GuildRole struct {
	ID           string  `json:"id"`
	Color        int32   `json:"color"`
	Colors       any     `json:"colors"`
	Description  *string `json:"description,omitempty"`
	Flags        int32   `json:"flags"`
	Hoist        bool    `json:"hoist"`
	Icon         *string `json:"icon,omitempty"`
	Managed      bool    `json:"managed"`
	Mentionable  bool    `json:"mentionable"`
	Name         string  `json:"name"`
	Permissions  string  `json:"permissions"`
	Position     int32   `json:"position"`
	Tags         any     `json:"tags,omitempty"`
	UnicodeEmoji *string `json:"unicode_emoji,omitempty"`
}

// GuildRoleColors
type GuildRoleColors struct {
	PrimaryColor   int32  `json:"primary_color"`
	SecondaryColor *int32 `json:"secondary_color,omitempty"`
	TertiaryColor  *int32 `json:"tertiary_color,omitempty"`
}

// GuildRoleTags
type GuildRoleTags struct {
	AvailableForPurchase  any    `json:"available_for_purchase,omitempty"`
	BotID                 string `json:"bot_id,omitempty"`
	GuildConnections      any    `json:"guild_connections,omitempty"`
	IntegrationID         string `json:"integration_id,omitempty"`
	PremiumSubscriber     any    `json:"premium_subscriber,omitempty"`
	SubscriptionListingID string `json:"subscription_listing_id,omitempty"`
}

// GuildScheduledEventEntityTypes
type GuildScheduledEventEntityTypes int

const (
	GuildScheduledEventEntityTypes0 GuildScheduledEventEntityTypes = 0
	GuildScheduledEventEntityTypes1 GuildScheduledEventEntityTypes = 1
	GuildScheduledEventEntityTypes2 GuildScheduledEventEntityTypes = 2
	GuildScheduledEventEntityTypes3 GuildScheduledEventEntityTypes = 3
)

// GuildScheduledEventPrivacyLevels
type GuildScheduledEventPrivacyLevels int

const (
	GuildScheduledEventPrivacyLevels2 GuildScheduledEventPrivacyLevels = 2
)

// GuildScheduledEventStatuses
type GuildScheduledEventStatuses int

const (
	GuildScheduledEventStatuses1 GuildScheduledEventStatuses = 1
	GuildScheduledEventStatuses2 GuildScheduledEventStatuses = 2
	GuildScheduledEventStatuses3 GuildScheduledEventStatuses = 3
	GuildScheduledEventStatuses4 GuildScheduledEventStatuses = 4
)

// GuildSticker
type GuildSticker struct {
	ID          string  `json:"id"`
	Available   bool    `json:"available"`
	Description *string `json:"description,omitempty"`
	FormatType  any     `json:"format_type,omitempty"`
	GuildID     string  `json:"guild_id"`
	Name        string  `json:"name"`
	Tags        string  `json:"tags"`
	Type        int32   `json:"type"`
	User        any     `json:"user,omitempty"`
}

// GuildSubscriptionIntegration
type GuildSubscriptionIntegration struct {
	ID      string  `json:"id"`
	Account any     `json:"account"`
	Enabled bool    `json:"enabled"`
	Name    *string `json:"name,omitempty"`
	Type    string  `json:"type"`
}

// GuildTemplate
type GuildTemplate struct {
	Code                  string    `json:"code"`
	CreatedAt             time.Time `json:"created_at"`
	Creator               any       `json:"creator,omitempty"`
	CreatorID             string    `json:"creator_id"`
	Description           *string   `json:"description,omitempty"`
	IsDirty               *bool     `json:"is_dirty,omitempty"`
	Name                  string    `json:"name"`
	SerializedSourceGuild any       `json:"serialized_source_guild"`
	SourceGuildID         string    `json:"source_guild_id"`
	UpdatedAt             time.Time `json:"updated_at"`
	UsageCount            int32     `json:"usage_count"`
}

// GuildTemplateChannel
type GuildTemplateChannel struct {
	ID                            *int32  `json:"id,omitempty"`
	AvailableTags                 []any   `json:"available_tags,omitempty"`
	Bitrate                       int32   `json:"bitrate"`
	DefaultAutoArchiveDuration    any     `json:"default_auto_archive_duration,omitempty"`
	DefaultForumLayout            any     `json:"default_forum_layout,omitempty"`
	DefaultReactionEmoji          any     `json:"default_reaction_emoji,omitempty"`
	DefaultSortOrder              any     `json:"default_sort_order,omitempty"`
	DefaultTagSetting             any     `json:"default_tag_setting,omitempty"`
	DefaultThreadRateLimitPerUser *int32  `json:"default_thread_rate_limit_per_user,omitempty"`
	IconEmoji                     any     `json:"icon_emoji,omitempty"`
	Name                          *string `json:"name,omitempty"`
	Nsfw                          bool    `json:"nsfw"`
	ParentID                      any     `json:"parent_id,omitempty"`
	PermissionOverwrites          []any   `json:"permission_overwrites"`
	Position                      *int32  `json:"position,omitempty"`
	RateLimitPerUser              int32   `json:"rate_limit_per_user"`
	Template                      string  `json:"template"`
	ThemeColor                    *int32  `json:"theme_color,omitempty"`
	Topic                         *string `json:"topic,omitempty"`
	Type                          int32   `json:"type"`
	UserLimit                     int32   `json:"user_limit"`
}

// GuildTemplateChannelTags
type GuildTemplateChannelTags struct {
	ID        *int32  `json:"id,omitempty"`
	EmojiID   any     `json:"emoji_id,omitempty"`
	EmojiName *string `json:"emoji_name,omitempty"`
	Moderated *bool   `json:"moderated,omitempty"`
	Name      string  `json:"name"`
}

// GuildTemplateRole
type GuildTemplateRole struct {
	ID           int32   `json:"id"`
	Color        int32   `json:"color"`
	Colors       any     `json:"colors,omitempty"`
	Hoist        bool    `json:"hoist"`
	Icon         *string `json:"icon,omitempty"`
	Mentionable  bool    `json:"mentionable"`
	Name         string  `json:"name"`
	Permissions  string  `json:"permissions"`
	UnicodeEmoji *string `json:"unicode_emoji,omitempty"`
}

// GuildTemplateRoleColors
type GuildTemplateRoleColors struct {
	PrimaryColor   int32  `json:"primary_color"`
	SecondaryColor *int32 `json:"secondary_color,omitempty"`
	TertiaryColor  *int32 `json:"tertiary_color,omitempty"`
}

// GuildTemplateSnapshot
type GuildTemplateSnapshot struct {
	AfkChannelID                any     `json:"afk_channel_id,omitempty"`
	AfkTimeout                  int32   `json:"afk_timeout"`
	Channels                    []any   `json:"channels"`
	DefaultMessageNotifications int32   `json:"default_message_notifications"`
	Description                 *string `json:"description,omitempty"`
	ExplicitContentFilter       int32   `json:"explicit_content_filter"`
	Name                        string  `json:"name"`
	PreferredLocale             string  `json:"preferred_locale"`
	Region                      *string `json:"region,omitempty"`
	Roles                       []any   `json:"roles"`
	SystemChannelFlags          int32   `json:"system_channel_flags"`
	SystemChannelID             any     `json:"system_channel_id,omitempty"`
	VerificationLevel           int32   `json:"verification_level"`
}

// GuildWelcomeChannel
type GuildWelcomeChannel struct {
	ChannelID   string  `json:"channel_id"`
	Description string  `json:"description"`
	EmojiID     any     `json:"emoji_id,omitempty"`
	EmojiName   *string `json:"emoji_name,omitempty"`
}

// GuildWelcomeScreen
type GuildWelcomeScreen struct {
	Description     *string `json:"description,omitempty"`
	WelcomeChannels []any   `json:"welcome_channels"`
}

// GuildWelcomeScreenChannel
type GuildWelcomeScreenChannel struct {
	ChannelID   string  `json:"channel_id"`
	Description string  `json:"description"`
	EmojiID     any     `json:"emoji_id,omitempty"`
	EmojiName   *string `json:"emoji_name,omitempty"`
}

// GuildWithCounts
type GuildWithCounts struct {
	ID                          string   `json:"id"`
	AfkChannelID                any      `json:"afk_channel_id,omitempty"`
	AfkTimeout                  int32    `json:"afk_timeout"`
	ApplicationID               any      `json:"application_id,omitempty"`
	ApproximateMemberCount      *int32   `json:"approximate_member_count,omitempty"`
	ApproximatePresenceCount    *int32   `json:"approximate_presence_count,omitempty"`
	Banner                      *string  `json:"banner,omitempty"`
	DefaultMessageNotifications int32    `json:"default_message_notifications"`
	Description                 *string  `json:"description,omitempty"`
	DiscoverySplash             *string  `json:"discovery_splash,omitempty"`
	Emojis                      []any    `json:"emojis"`
	ExplicitContentFilter       int32    `json:"explicit_content_filter"`
	Features                    []string `json:"features"`
	HomeHeader                  *string  `json:"home_header,omitempty"`
	Icon                        *string  `json:"icon,omitempty"`
	MaxMembers                  int32    `json:"max_members"`
	MaxPresences                *int32   `json:"max_presences,omitempty"`
	MaxStageVideoChannelUsers   int32    `json:"max_stage_video_channel_users"`
	MaxVideoChannelUsers        int32    `json:"max_video_channel_users"`
	MfaLevel                    int32    `json:"mfa_level"`
	Name                        string   `json:"name"`
	Nsfw                        bool     `json:"nsfw"`
	NsfwLevel                   int32    `json:"nsfw_level"`
	OwnerID                     string   `json:"owner_id"`
	PreferredLocale             string   `json:"preferred_locale"`
	PremiumProgressBarEnabled   bool     `json:"premium_progress_bar_enabled"`
	PremiumSubscriptionCount    int32    `json:"premium_subscription_count"`
	PremiumTier                 int32    `json:"premium_tier"`
	PublicUpdatesChannelID      any      `json:"public_updates_channel_id,omitempty"`
	Region                      string   `json:"region"`
	Roles                       []any    `json:"roles"`
	RulesChannelID              any      `json:"rules_channel_id,omitempty"`
	SafetyAlertsChannelID       any      `json:"safety_alerts_channel_id,omitempty"`
	Splash                      *string  `json:"splash,omitempty"`
	Stickers                    []any    `json:"stickers"`
	SystemChannelFlags          int32    `json:"system_channel_flags"`
	SystemChannelID             any      `json:"system_channel_id,omitempty"`
	VanityURLCode               *string  `json:"vanity_url_code,omitempty"`
	VerificationLevel           int32    `json:"verification_level"`
	WidgetChannelID             any      `json:"widget_channel_id,omitempty"`
	WidgetEnabled               bool     `json:"widget_enabled"`
}
