// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// IncomingWebhookInteractionOptions
type IncomingWebhookInteractionOptions struct {
	AllowedMentions any     `json:"allowed_mentions,omitempty"`
	Attachments     []any   `json:"attachments,omitempty"`
	Components      []any   `json:"components,omitempty"`
	Content         *string `json:"content,omitempty"`
	Embeds          []any   `json:"embeds,omitempty"`
	Flags           *int64  `json:"flags,omitempty"`
	Poll            any     `json:"poll,omitempty"`
	Tts             *bool   `json:"tts,omitempty"`
}

// IncomingWebhookOptionsPartial
type IncomingWebhookOptionsPartial struct {
	AllowedMentions any      `json:"allowed_mentions,omitempty"`
	AppliedTags     []string `json:"applied_tags,omitempty"`
	Attachments     []any    `json:"attachments,omitempty"`
	AvatarURL       *string  `json:"avatar_url,omitempty"`
	Components      []any    `json:"components,omitempty"`
	Content         *string  `json:"content,omitempty"`
	Embeds          []any    `json:"embeds,omitempty"`
	Flags           *int64   `json:"flags,omitempty"`
	Poll            any      `json:"poll,omitempty"`
	ThreadName      *string  `json:"thread_name,omitempty"`
	Tts             *bool    `json:"tts,omitempty"`
	Username        *string  `json:"username,omitempty"`
}

// IncomingWebhookUpdateForInteractionCallbackOptionsPartial
type IncomingWebhookUpdateForInteractionCallbackOptionsPartial struct {
	AllowedMentions any     `json:"allowed_mentions,omitempty"`
	Attachments     []any   `json:"attachments,omitempty"`
	Components      []any   `json:"components,omitempty"`
	Content         *string `json:"content,omitempty"`
	Embeds          []any   `json:"embeds,omitempty"`
	Flags           *int64  `json:"flags,omitempty"`
}

// IncomingWebhookUpdateOptionsPartial
type IncomingWebhookUpdateOptionsPartial struct {
	AllowedMentions any     `json:"allowed_mentions,omitempty"`
	Attachments     []any   `json:"attachments,omitempty"`
	Components      []any   `json:"components,omitempty"`
	Content         *string `json:"content,omitempty"`
	Embeds          []any   `json:"embeds,omitempty"`
	Flags           *int64  `json:"flags,omitempty"`
	Poll            any     `json:"poll,omitempty"`
}
