// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// InnerErrors
type InnerErrors struct {
	Errors []any `json:"_errors"` // The list of errors for this field
}
