// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// Interaction
type Interaction struct {
	ID                       string `json:"id"`
	ChannelID                string `json:"channel_id,omitempty"`
	GuildID                  string `json:"guild_id,omitempty"`
	ResponseMessageEphemeral bool   `json:"response_message_ephemeral,omitempty"`
	ResponseMessageID        string `json:"response_message_id,omitempty"`
	ResponseMessageLoading   bool   `json:"response_message_loading,omitempty"`
	Type                     int32  `json:"type"`
}

// InteractionApplicationCommandAutocompleteCallbackIntegerData
type InteractionApplicationCommandAutocompleteCallbackIntegerData struct {
	Choices []any `json:"choices,omitempty"`
}

// InteractionApplicationCommandAutocompleteCallbackNumberData
type InteractionApplicationCommandAutocompleteCallbackNumberData struct {
	Choices []any `json:"choices,omitempty"`
}

// InteractionApplicationCommandAutocompleteCallbackStringData
type InteractionApplicationCommandAutocompleteCallbackStringData struct {
	Choices []any `json:"choices,omitempty"`
}

// InteractionCallback
type InteractionCallback struct {
	Interaction any `json:"interaction"`
	Resource    any `json:"resource,omitempty"`
}

// InteractionCallbackTypes
type InteractionCallbackTypes int

const (
	InteractionCallbackTypes1  InteractionCallbackTypes = 1
	InteractionCallbackTypes4  InteractionCallbackTypes = 4
	InteractionCallbackTypes5  InteractionCallbackTypes = 5
	InteractionCallbackTypes6  InteractionCallbackTypes = 6
	InteractionCallbackTypes7  InteractionCallbackTypes = 7
	InteractionCallbackTypes8  InteractionCallbackTypes = 8
	InteractionCallbackTypes9  InteractionCallbackTypes = 9
	InteractionCallbackTypes12 InteractionCallbackTypes = 12
)

// InteractionContextType
type InteractionContextType int

const (
	InteractionContextType0 InteractionContextType = 0
	InteractionContextType1 InteractionContextType = 1
	InteractionContextType2 InteractionContextType = 2
)

// InteractionTypes
type InteractionTypes int

const (
	InteractionTypes1 InteractionTypes = 1
	InteractionTypes2 InteractionTypes = 2
	InteractionTypes3 InteractionTypes = 3
	InteractionTypes4 InteractionTypes = 4
	InteractionTypes5 InteractionTypes = 5
)
