// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// IntegrationApplication
type IntegrationApplication struct {
	ID           string  `json:"id"`
	Bot          any     `json:"bot,omitempty"`
	CoverImage   string  `json:"cover_image,omitempty"`
	Description  string  `json:"description"`
	Icon         *string `json:"icon,omitempty"`
	Name         string  `json:"name"`
	PrimarySkuID string  `json:"primary_sku_id,omitempty"`
	Type         any     `json:"type,omitempty"`
}

// IntegrationExpireBehaviorTypes
type IntegrationExpireBehaviorTypes int

const (
	IntegrationExpireBehaviorTypes0 IntegrationExpireBehaviorTypes = 0
	IntegrationExpireBehaviorTypes1 IntegrationExpireBehaviorTypes = 1
)

// IntegrationExpireGracePeriodTypes
type IntegrationExpireGracePeriodTypes int

const (
	IntegrationExpireGracePeriodTypes1  IntegrationExpireGracePeriodTypes = 1
	IntegrationExpireGracePeriodTypes3  IntegrationExpireGracePeriodTypes = 3
	IntegrationExpireGracePeriodTypes7  IntegrationExpireGracePeriodTypes = 7
	IntegrationExpireGracePeriodTypes14 IntegrationExpireGracePeriodTypes = 14
	IntegrationExpireGracePeriodTypes30 IntegrationExpireGracePeriodTypes = 30
)

// IntegrationTypes
type IntegrationTypes string

const (
	IntegrationTypesDiscord           IntegrationTypes = "discord"
	IntegrationTypesTwitch            IntegrationTypes = "twitch"
	IntegrationTypesYoutube           IntegrationTypes = "youtube"
	IntegrationTypesGuildSubscription IntegrationTypes = "guild_subscription"
)
