// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// InviteApplication
type InviteApplication struct {
	ID                     string         `json:"id"`
	Bot                    any            `json:"bot,omitempty"`
	BotPublic              bool           `json:"bot_public,omitempty"`
	BotRequireCodeGrant    bool           `json:"bot_require_code_grant,omitempty"`
	CoverImage             string         `json:"cover_image,omitempty"`
	CustomInstallURL       string         `json:"custom_install_url,omitempty"`
	Description            string         `json:"description"`
	Flags                  int32          `json:"flags"`
	GuildID                string         `json:"guild_id,omitempty"`
	Icon                   *string        `json:"icon,omitempty"`
	InstallParams          any            `json:"install_params,omitempty"`
	IntegrationTypesConfig map[string]any `json:"integration_types_config,omitempty"`
	MaxParticipants        *int32         `json:"max_participants,omitempty"`
	Name                   string         `json:"name"`
	PrimarySkuID           string         `json:"primary_sku_id,omitempty"`
	PrivacyPolicyURL       string         `json:"privacy_policy_url,omitempty"`
	RpcOrigins             []*string      `json:"rpc_origins,omitempty"`
	Slug                   string         `json:"slug,omitempty"`
	Tags                   []string       `json:"tags,omitempty"`
	TermsOfServiceURL      string         `json:"terms_of_service_url,omitempty"`
	Type                   any            `json:"type,omitempty"`
	VerifyKey              string         `json:"verify_key"`
}

// InviteChannel
type InviteChannel struct {
	ID         string  `json:"id"`
	Icon       string  `json:"icon,omitempty"`
	Name       *string `json:"name,omitempty"`
	Recipients []any   `json:"recipients,omitempty"`
	Type       int32   `json:"type"`
}

// InviteChannelRecipient
type InviteChannelRecipient struct {
	Username string `json:"username"`
}

// InviteGuild
type InviteGuild struct {
	ID                       string   `json:"id"`
	Banner                   *string  `json:"banner,omitempty"`
	Description              *string  `json:"description,omitempty"`
	Features                 []string `json:"features"`
	Icon                     *string  `json:"icon,omitempty"`
	Name                     string   `json:"name"`
	Nsfw                     *bool    `json:"nsfw,omitempty"`
	NsfwLevel                any      `json:"nsfw_level,omitempty"`
	PremiumSubscriptionCount int32    `json:"premium_subscription_count"`
	Splash                   *string  `json:"splash,omitempty"`
	VanityURLCode            *string  `json:"vanity_url_code,omitempty"`
	VerificationLevel        any      `json:"verification_level,omitempty"`
}

// InviteTargetTypes
type InviteTargetTypes int

const (
	InviteTargetTypes1 InviteTargetTypes = 1
	InviteTargetTypes2 InviteTargetTypes = 2
	InviteTargetTypes3 InviteTargetTypes = 3
)

// InviteTypes
type InviteTypes int

const (
	InviteTypes0 InviteTypes = 0
	InviteTypes1 InviteTypes = 1
	InviteTypes2 InviteTypes = 2
)
