// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// LabelComponentForModalOptions
type LabelComponentForModalOptions struct {
	ID          *int32  `json:"id,omitempty"`
	Component   any     `json:"component"`
	Description *string `json:"description,omitempty"`
	Label       string  `json:"label"`
	Type        int32   `json:"type"`
}
