// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// LaunchActivityInteractionCallback
type LaunchActivityInteractionCallback struct {
	Type int32 `json:"type"`
}

// LaunchActivityInteractionCallbackOptions
type LaunchActivityInteractionCallbackOptions struct {
	Type int32 `json:"type"`
}
