// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// ListApplicationEmojis
type ListApplicationEmojis struct {
	Items []any `json:"items"`
}

// ListGuildSoundboardSounds
type ListGuildSoundboardSounds struct {
	Items []any `json:"items"`
}
