// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// Lobby
type Lobby struct {
	ID                       string            `json:"id"`
	ApplicationID            string            `json:"application_id"`
	Flags                    int64             `json:"flags"`
	LinkedChannel            any               `json:"linked_channel,omitempty"`
	Members                  []any             `json:"members"`
	Metadata                 map[string]string `json:"metadata,omitempty"`
	OverrideEventWebhooksURL *string           `json:"override_event_webhooks_url,omitempty"`
}

// LobbyGuildInvite
type LobbyGuildInvite struct {
	Code string `json:"code"`
}

// LobbyMember
type LobbyMember struct {
	ID       string            `json:"id"`
	Flags    int32             `json:"flags"`
	Metadata map[string]string `json:"metadata,omitempty"`
}

// LobbyMemberOptions
type LobbyMemberOptions struct {
	ID       string            `json:"id"`
	Flags    any               `json:"flags,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
}

// LobbyMessage
type LobbyMessage struct {
	ID            string            `json:"id"`
	ApplicationID string            `json:"application_id,omitempty"`
	Author        any               `json:"author"`
	ChannelID     string            `json:"channel_id"`
	Content       string            `json:"content"`
	Flags         int32             `json:"flags"`
	LobbyID       string            `json:"lobby_id"`
	Metadata      map[string]string `json:"metadata,omitempty"`
	Type          int32             `json:"type"`
}
