// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// MediaGalleryComponent
type MediaGalleryComponent struct {
	ID    int32 `json:"id"`
	Items []any `json:"items"`
	Type  int32 `json:"type"`
}

// MediaGalleryComponentForMessageOptions
type MediaGalleryComponentForMessageOptions struct {
	ID    *int32 `json:"id,omitempty"`
	Items []any  `json:"items"`
	Type  int32  `json:"type"`
}

// MediaGalleryItem
type MediaGalleryItem struct {
	Description *string `json:"description,omitempty"`
	Media       any     `json:"media"`
	Spoiler     bool    `json:"spoiler"`
}

// MediaGalleryItemOptions
type MediaGalleryItemOptions struct {
	Description *string `json:"description,omitempty"`
	Media       any     `json:"media"`
	Spoiler     *bool   `json:"spoiler,omitempty"`
}
