// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// MentionableSelectComponent
type MentionableSelectComponent struct {
	ID            int32  `json:"id"`
	CustomID      string `json:"custom_id"`
	DefaultValues []any  `json:"default_values,omitempty"`
	Disabled      bool   `json:"disabled,omitempty"`
	MaxValues     *int32 `json:"max_values,omitempty"`
	MinValues     *int32 `json:"min_values,omitempty"`
	Placeholder   string `json:"placeholder,omitempty"`
	Type          int32  `json:"type"`
}

// MentionableSelectComponentForMessageOptions
type MentionableSelectComponentForMessageOptions struct {
	ID            *int32  `json:"id,omitempty"`
	CustomID      string  `json:"custom_id"`
	DefaultValues []any   `json:"default_values,omitempty"`
	Disabled      *bool   `json:"disabled,omitempty"`
	MaxValues     *int64  `json:"max_values,omitempty"`
	MinValues     *int64  `json:"min_values,omitempty"`
	Placeholder   *string `json:"placeholder,omitempty"`
	Required      *bool   `json:"required,omitempty"`
	Type          int32   `json:"type"`
}

// MentionableSelectComponentForModalOptions
type MentionableSelectComponentForModalOptions struct {
	ID            *int32  `json:"id,omitempty"`
	CustomID      string  `json:"custom_id"`
	DefaultValues []any   `json:"default_values,omitempty"`
	Disabled      *bool   `json:"disabled,omitempty"`
	MaxValues     *int64  `json:"max_values,omitempty"`
	MinValues     *int64  `json:"min_values,omitempty"`
	Placeholder   *string `json:"placeholder,omitempty"`
	Required      *bool   `json:"required,omitempty"`
	Type          int32   `json:"type"`
}
