// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// Message
type Message struct {
	ID                   string     `json:"id"`
	Activity             any        `json:"activity,omitempty"`
	Application          any        `json:"application,omitempty"`
	ApplicationID        string     `json:"application_id,omitempty"`
	Attachments          []any      `json:"attachments"`
	Author               any        `json:"author"`
	Call                 any        `json:"call,omitempty"`
	ChannelID            string     `json:"channel_id"`
	Components           []any      `json:"components"`
	Content              string     `json:"content"`
	EditedTimestamp      *time.Time `json:"edited_timestamp,omitempty"`
	Embeds               []any      `json:"embeds"`
	Flags                int32      `json:"flags"`
	Interaction          any        `json:"interaction,omitempty"`
	InteractionMetadata  any        `json:"interaction_metadata,omitempty"`
	MentionChannels      []any      `json:"mention_channels,omitempty"`
	MentionEveryone      bool       `json:"mention_everyone"`
	MentionRoles         []string   `json:"mention_roles"`
	Mentions             []any      `json:"mentions"`
	MessageReference     any        `json:"message_reference,omitempty"`
	MessageSnapshots     []any      `json:"message_snapshots,omitempty"`
	Nonce                any        `json:"nonce,omitempty"`
	Pinned               bool       `json:"pinned"`
	Poll                 any        `json:"poll,omitempty"`
	Position             int32      `json:"position,omitempty"`
	PurchaseNotification any        `json:"purchase_notification,omitempty"`
	Reactions            []any      `json:"reactions,omitempty"`
	ReferencedMessage    any        `json:"referenced_message,omitempty"`
	Resolved             any        `json:"resolved,omitempty"`
	RoleSubscriptionData any        `json:"role_subscription_data,omitempty"`
	SharedClientTheme    any        `json:"shared_client_theme,omitempty"`
	StickerItems         []any      `json:"sticker_items,omitempty"`
	Stickers             []any      `json:"stickers,omitempty"`
	Thread               any        `json:"thread,omitempty"`
	Timestamp            time.Time  `json:"timestamp"`
	Tts                  bool       `json:"tts"`
	Type                 int32      `json:"type"`
	WebhookID            string     `json:"webhook_id,omitempty"`
}

// MessageActivity
type MessageActivity struct {
}

// MessageAllowedMentionsOptions
type MessageAllowedMentionsOptions struct {
	Parse       []any `json:"parse,omitempty"`
	RepliedUser *bool `json:"replied_user,omitempty"`
	Roles       []any `json:"roles,omitempty"`
	Users       []any `json:"users,omitempty"`
}

// MessageAttachment
type MessageAttachment struct {
	ID               string    `json:"id"`
	Application      any       `json:"application,omitempty"`
	ClipCreatedAt    time.Time `json:"clip_created_at,omitempty"`
	ClipParticipants []any     `json:"clip_participants,omitempty"`
	ContentType      string    `json:"content_type,omitempty"`
	Description      string    `json:"description,omitempty"`
	DurationSecs     float64   `json:"duration_secs,omitempty"`
	Ephemeral        bool      `json:"ephemeral,omitempty"`
	Filename         string    `json:"filename"`
	Height           int32     `json:"height,omitempty"`
	ProxyURL         string    `json:"proxy_url"`
	Size             int32     `json:"size"`
	Title            *string   `json:"title,omitempty"`
	URL              string    `json:"url"`
	Waveform         string    `json:"waveform,omitempty"`
	Width            int32     `json:"width,omitempty"`
}

// MessageAttachmentOptions
type MessageAttachmentOptions struct {
	ID           string   `json:"id"`
	Description  *string  `json:"description,omitempty"`
	DurationSecs *float64 `json:"duration_secs,omitempty"`
	Filename     *string  `json:"filename,omitempty"`
	IsRemix      *bool    `json:"is_remix,omitempty"`
	Title        *string  `json:"title,omitempty"`
	Waveform     *string  `json:"waveform,omitempty"`
}

// MessageCall
type MessageCall struct {
	EndedTimestamp *time.Time `json:"ended_timestamp,omitempty"`
	Participants   []string   `json:"participants"`
}

// MessageComponentInteractionMetadata
type MessageComponentInteractionMetadata struct {
	ID                           string            `json:"id"`
	AuthorizingIntegrationOwners map[string]string `json:"authorizing_integration_owners"`
	InteractedMessageID          string            `json:"interacted_message_id"`
	OriginalResponseMessageID    string            `json:"original_response_message_id,omitempty"`
	Type                         int32             `json:"type"`
	User                         any               `json:"user,omitempty"`
}

// MessageComponentSeparatorSpacingSize
type MessageComponentSeparatorSpacingSize int

const (
	MessageComponentSeparatorSpacingSize1 MessageComponentSeparatorSpacingSize = 1
	MessageComponentSeparatorSpacingSize2 MessageComponentSeparatorSpacingSize = 2
)

// MessageComponentTypes
type MessageComponentTypes int

const (
	MessageComponentTypes1  MessageComponentTypes = 1
	MessageComponentTypes2  MessageComponentTypes = 2
	MessageComponentTypes3  MessageComponentTypes = 3
	MessageComponentTypes4  MessageComponentTypes = 4
	MessageComponentTypes5  MessageComponentTypes = 5
	MessageComponentTypes6  MessageComponentTypes = 6
	MessageComponentTypes7  MessageComponentTypes = 7
	MessageComponentTypes8  MessageComponentTypes = 8
	MessageComponentTypes9  MessageComponentTypes = 9
	MessageComponentTypes10 MessageComponentTypes = 10
	MessageComponentTypes11 MessageComponentTypes = 11
	MessageComponentTypes12 MessageComponentTypes = 12
	MessageComponentTypes13 MessageComponentTypes = 13
	MessageComponentTypes14 MessageComponentTypes = 14
	MessageComponentTypes17 MessageComponentTypes = 17
	MessageComponentTypes18 MessageComponentTypes = 18
	MessageComponentTypes19 MessageComponentTypes = 19
)

// MessageCreateOptions
type MessageCreateOptions struct {
	AllowedMentions   any      `json:"allowed_mentions,omitempty"`
	Attachments       []any    `json:"attachments,omitempty"`
	Components        []any    `json:"components,omitempty"`
	ConfettiPotion    any      `json:"confetti_potion,omitempty"`
	Content           *string  `json:"content,omitempty"`
	Embeds            []any    `json:"embeds,omitempty"`
	EnforceNonce      *bool    `json:"enforce_nonce,omitempty"`
	Flags             *int64   `json:"flags,omitempty"`
	MessageReference  any      `json:"message_reference,omitempty"`
	Nonce             any      `json:"nonce,omitempty"`
	Poll              any      `json:"poll,omitempty"`
	SharedClientTheme any      `json:"shared_client_theme,omitempty"`
	StickerIds        []string `json:"sticker_ids,omitempty"`
	Tts               *bool    `json:"tts,omitempty"`
}

// MessageEditOptionsPartial
type MessageEditOptionsPartial struct {
	AllowedMentions any      `json:"allowed_mentions,omitempty"`
	Attachments     []any    `json:"attachments,omitempty"`
	Components      []any    `json:"components,omitempty"`
	Content         *string  `json:"content,omitempty"`
	Embeds          []any    `json:"embeds,omitempty"`
	Flags           *int64   `json:"flags,omitempty"`
	StickerIds      []string `json:"sticker_ids,omitempty"`
}

// MessageEmbed
type MessageEmbed struct {
	Author      any       `json:"author,omitempty"`
	Color       int32     `json:"color,omitempty"`
	Description string    `json:"description,omitempty"`
	Fields      []any     `json:"fields,omitempty"`
	Footer      any       `json:"footer,omitempty"`
	Image       any       `json:"image,omitempty"`
	Provider    any       `json:"provider,omitempty"`
	Thumbnail   any       `json:"thumbnail,omitempty"`
	Timestamp   time.Time `json:"timestamp,omitempty"`
	Title       string    `json:"title,omitempty"`
	Type        string    `json:"type"`
	URL         string    `json:"url,omitempty"`
	Video       any       `json:"video,omitempty"`
}

// MessageEmbedAuthor
type MessageEmbedAuthor struct {
	IconURL      string `json:"icon_url,omitempty"`
	Name         string `json:"name"`
	ProxyIconURL string `json:"proxy_icon_url,omitempty"`
	URL          string `json:"url,omitempty"`
}

// MessageEmbedField
type MessageEmbedField struct {
	Inline bool   `json:"inline"`
	Name   string `json:"name"`
	Value  string `json:"value"`
}

// MessageEmbedFooter
type MessageEmbedFooter struct {
	IconURL      string `json:"icon_url,omitempty"`
	ProxyIconURL string `json:"proxy_icon_url,omitempty"`
	Text         string `json:"text"`
}

// MessageEmbedImage
type MessageEmbedImage struct {
	ContentType        string `json:"content_type,omitempty"`
	Description        string `json:"description,omitempty"`
	Flags              int64  `json:"flags,omitempty"`
	Height             int64  `json:"height,omitempty"`
	Placeholder        string `json:"placeholder,omitempty"`
	PlaceholderVersion int64  `json:"placeholder_version,omitempty"`
	ProxyURL           string `json:"proxy_url,omitempty"`
	URL                string `json:"url,omitempty"`
	Width              int64  `json:"width,omitempty"`
}

// MessageEmbedProvider
type MessageEmbedProvider struct {
	Name string `json:"name"`
	URL  string `json:"url,omitempty"`
}

// MessageEmbedVideo
type MessageEmbedVideo struct {
	ContentType        string `json:"content_type,omitempty"`
	Description        string `json:"description,omitempty"`
	Flags              int64  `json:"flags,omitempty"`
	Height             int64  `json:"height,omitempty"`
	Placeholder        string `json:"placeholder,omitempty"`
	PlaceholderVersion int64  `json:"placeholder_version,omitempty"`
	ProxyURL           string `json:"proxy_url,omitempty"`
	URL                string `json:"url,omitempty"`
	Width              int64  `json:"width,omitempty"`
}

// MessageInteraction
type MessageInteraction struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	NameLocalized string `json:"name_localized,omitempty"`
	Type          int32  `json:"type"`
	User          any    `json:"user,omitempty"`
}

// MessageMentionChannel
type MessageMentionChannel struct {
	ID      string `json:"id"`
	GuildID string `json:"guild_id"`
	Name    string `json:"name"`
	Type    int32  `json:"type"`
}

// MessageReaction
type MessageReaction struct {
	BurstColors  []string `json:"burst_colors"`
	Count        int32    `json:"count"`
	CountDetails any      `json:"count_details"`
	Emoji        any      `json:"emoji"`
	Me           bool     `json:"me"`
	MeBurst      bool     `json:"me_burst"`
}

// MessageReactionCountDetails
type MessageReactionCountDetails struct {
	Burst  int32 `json:"burst"`
	Normal int32 `json:"normal"`
}

// MessageReactionEmoji
type MessageReactionEmoji struct {
	ID       any     `json:"id,omitempty"`
	Animated bool    `json:"animated,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// MessageReference
type MessageReference struct {
	ChannelID string `json:"channel_id"`
	GuildID   string `json:"guild_id,omitempty"`
	MessageID string `json:"message_id,omitempty"`
	Type      int32  `json:"type"`
}

// MessageReferenceOptions
type MessageReferenceOptions struct {
	ChannelID       any    `json:"channel_id,omitempty"`
	FailIfNotExists *bool  `json:"fail_if_not_exists,omitempty"`
	GuildID         any    `json:"guild_id,omitempty"`
	MessageID       string `json:"message_id"`
	Type            any    `json:"type,omitempty"`
}

// MessageReferenceType
type MessageReferenceType int

const (
	MessageReferenceType0 MessageReferenceType = 0
)

// MessageRoleSubscriptionData
type MessageRoleSubscriptionData struct {
	IsRenewal                 bool   `json:"is_renewal"`
	RoleSubscriptionListingID string `json:"role_subscription_listing_id"`
	TierName                  string `json:"tier_name"`
	TotalMonthsSubscribed     int32  `json:"total_months_subscribed"`
}

// MessageShareCustomUserThemeBaseTheme
type MessageShareCustomUserThemeBaseTheme int

const (
	MessageShareCustomUserThemeBaseTheme0 MessageShareCustomUserThemeBaseTheme = 0
	MessageShareCustomUserThemeBaseTheme1 MessageShareCustomUserThemeBaseTheme = 1
	MessageShareCustomUserThemeBaseTheme2 MessageShareCustomUserThemeBaseTheme = 2
	MessageShareCustomUserThemeBaseTheme3 MessageShareCustomUserThemeBaseTheme = 3
	MessageShareCustomUserThemeBaseTheme4 MessageShareCustomUserThemeBaseTheme = 4
)

// MessageSnapshot
type MessageSnapshot struct {
	Message any `json:"message"`
}

// MessageStickerItem
type MessageStickerItem struct {
	ID         string `json:"id"`
	FormatType int32  `json:"format_type"`
	Name       string `json:"name"`
}

// MessageType
type MessageType int

const (
	MessageType0  MessageType = 0
	MessageType1  MessageType = 1
	MessageType2  MessageType = 2
	MessageType3  MessageType = 3
	MessageType4  MessageType = 4
	MessageType5  MessageType = 5
	MessageType6  MessageType = 6
	MessageType7  MessageType = 7
	MessageType8  MessageType = 8
	MessageType9  MessageType = 9
	MessageType10 MessageType = 10
	MessageType11 MessageType = 11
	MessageType12 MessageType = 12
	MessageType14 MessageType = 14
	MessageType15 MessageType = 15
	MessageType16 MessageType = 16
	MessageType17 MessageType = 17
	MessageType18 MessageType = 18
	MessageType19 MessageType = 19
	MessageType20 MessageType = 20
	MessageType21 MessageType = 21
	MessageType22 MessageType = 22
	MessageType23 MessageType = 23
	MessageType24 MessageType = 24
	MessageType25 MessageType = 25
	MessageType26 MessageType = 26
	MessageType27 MessageType = 27
	MessageType28 MessageType = 28
	MessageType29 MessageType = 29
	MessageType31 MessageType = 31
	MessageType32 MessageType = 32
	MessageType36 MessageType = 36
	MessageType37 MessageType = 37
	MessageType38 MessageType = 38
	MessageType39 MessageType = 39
	MessageType46 MessageType = 46
	MessageType55 MessageType = 55
)
