// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// MetadataItemTypes
type MetadataItemTypes int

const (
	MetadataItemTypes1 MetadataItemTypes = 1
	MetadataItemTypes2 MetadataItemTypes = 2
	MetadataItemTypes3 MetadataItemTypes = 3
	MetadataItemTypes4 MetadataItemTypes = 4
	MetadataItemTypes5 MetadataItemTypes = 5
	MetadataItemTypes6 MetadataItemTypes = 6
	MetadataItemTypes7 MetadataItemTypes = 7
	MetadataItemTypes8 MetadataItemTypes = 8
)
