// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// MinimalContentMessage
type MinimalContentMessage struct {
	Attachments     []any      `json:"attachments"`
	Components      []any      `json:"components"`
	Content         string     `json:"content"`
	EditedTimestamp *time.Time `json:"edited_timestamp,omitempty"`
	Embeds          []any      `json:"embeds"`
	Flags           int32      `json:"flags"`
	MentionRoles    []string   `json:"mention_roles"`
	Mentions        []any      `json:"mentions"`
	StickerItems    []any      `json:"sticker_items,omitempty"`
	Stickers        []any      `json:"stickers,omitempty"`
	Timestamp       time.Time  `json:"timestamp"`
	Type            int32      `json:"type"`
}
