// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// MLSpamRule
type MLSpamRule struct {
	ID              string   `json:"id"`
	Actions         []any    `json:"actions"`
	CreatorID       string   `json:"creator_id"`
	Enabled         bool     `json:"enabled"`
	EventType       int32    `json:"event_type"`
	ExemptChannels  []string `json:"exempt_channels"`
	ExemptRoles     []string `json:"exempt_roles"`
	GuildID         string   `json:"guild_id"`
	Name            string   `json:"name"`
	TriggerMetadata any      `json:"trigger_metadata"`
	TriggerType     int32    `json:"trigger_type"`
}

// MLSpamTriggerMetadata
type MLSpamTriggerMetadata struct {
}

// MLSpamUpsertOptions
type MLSpamUpsertOptions struct {
	Actions         []any    `json:"actions,omitempty"`
	Enabled         *bool    `json:"enabled,omitempty"`
	EventType       int32    `json:"event_type"`
	ExemptChannels  []string `json:"exempt_channels,omitempty"`
	ExemptRoles     []string `json:"exempt_roles,omitempty"`
	Name            string   `json:"name"`
	TriggerMetadata any      `json:"trigger_metadata,omitempty"`
	TriggerType     int32    `json:"trigger_type"`
}

// MLSpamUpsertOptionsPartial
type MLSpamUpsertOptionsPartial struct {
	Actions         []any    `json:"actions,omitempty"`
	Enabled         *bool    `json:"enabled,omitempty"`
	EventType       int32    `json:"event_type,omitempty"`
	ExemptChannels  []string `json:"exempt_channels,omitempty"`
	ExemptRoles     []string `json:"exempt_roles,omitempty"`
	Name            string   `json:"name,omitempty"`
	TriggerMetadata any      `json:"trigger_metadata,omitempty"`
	TriggerType     int32    `json:"trigger_type,omitempty"`
}
