// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// ModalInteractionCallbackOptions
type ModalInteractionCallbackOptions struct {
	Data any   `json:"data"`
	Type int32 `json:"type"`
}

// ModalInteractionCallbackOptionsData
type ModalInteractionCallbackOptionsData struct {
	Components []any  `json:"components"`
	CustomID   string `json:"custom_id"`
	Title      string `json:"title"`
}

// ModalSubmitInteractionMetadata
type ModalSubmitInteractionMetadata struct {
	ID                            string            `json:"id"`
	AuthorizingIntegrationOwners  map[string]string `json:"authorizing_integration_owners"`
	OriginalResponseMessageID     string            `json:"original_response_message_id,omitempty"`
	TriggeringInteractionMetadata any               `json:"triggering_interaction_metadata"`
	Type                          int32             `json:"type"`
	User                          any               `json:"user,omitempty"`
}
