// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// MyGuild
type MyGuild struct {
	ID                       string   `json:"id"`
	ApproximateMemberCount   *int32   `json:"approximate_member_count,omitempty"`
	ApproximatePresenceCount *int32   `json:"approximate_presence_count,omitempty"`
	Banner                   *string  `json:"banner,omitempty"`
	Features                 []string `json:"features"`
	Icon                     *string  `json:"icon,omitempty"`
	Name                     string   `json:"name"`
	Owner                    bool     `json:"owner"`
	Permissions              string   `json:"permissions"`
}
