// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// NewMemberAction
type NewMemberAction struct {
	ActionType  int32  `json:"action_type"`
	ChannelID   string `json:"channel_id"`
	Description string `json:"description"`
	Emoji       any    `json:"emoji,omitempty"`
	Icon        string `json:"icon,omitempty"`
	Title       string `json:"title"`
}

// NewMemberActionType
type NewMemberActionType int

const (
	NewMemberActionType0 NewMemberActionType = 0
	NewMemberActionType1 NewMemberActionType = 1
)
