// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// OAuth2GetAuthorization
type OAuth2GetAuthorization struct {
	Application any       `json:"application"`
	Expires     time.Time `json:"expires"`
	Scopes      []string  `json:"scopes"`
	User        any       `json:"user,omitempty"`
}

// OAuth2GetKeys
type OAuth2GetKeys struct {
	Keys []any `json:"keys"`
}

// OAuth2GetOpenIDConnectUserInfo
type OAuth2GetOpenIDConnectUserInfo struct {
	Email             *string `json:"email,omitempty"`
	EmailVerified     bool    `json:"email_verified,omitempty"`
	Locale            string  `json:"locale,omitempty"`
	Nickname          *string `json:"nickname,omitempty"`
	Picture           string  `json:"picture,omitempty"`
	PreferredUsername string  `json:"preferred_username,omitempty"`
	Sub               string  `json:"sub"`
}

// OAuth2Key
type OAuth2Key struct {
	Alg string `json:"alg"`
	E   string `json:"e"`
	Kid string `json:"kid"`
	Kty string `json:"kty"`
	N   string `json:"n"`
	Use string `json:"use"`
}

// OAuth2Scopes
type OAuth2Scopes string

const (
	OAuth2ScopesIdentify                              OAuth2Scopes = "identify"
	OAuth2ScopesEmail                                 OAuth2Scopes = "email"
	OAuth2ScopesConnections                           OAuth2Scopes = "connections"
	OAuth2ScopesGuilds                                OAuth2Scopes = "guilds"
	OAuth2ScopesGuildsJoin                            OAuth2Scopes = "guilds.join"
	OAuth2ScopesGuildsMembersRead                     OAuth2Scopes = "guilds.members.read"
	OAuth2ScopesGdmJoin                               OAuth2Scopes = "gdm.join"
	OAuth2ScopesBot                                   OAuth2Scopes = "bot"
	OAuth2ScopesRpc                                   OAuth2Scopes = "rpc"
	OAuth2ScopesRpcNotificationsRead                  OAuth2Scopes = "rpc.notifications.read"
	OAuth2ScopesRpcVoiceRead                          OAuth2Scopes = "rpc.voice.read"
	OAuth2ScopesRpcVoiceWrite                         OAuth2Scopes = "rpc.voice.write"
	OAuth2ScopesRpcVideoRead                          OAuth2Scopes = "rpc.video.read"
	OAuth2ScopesRpcVideoWrite                         OAuth2Scopes = "rpc.video.write"
	OAuth2ScopesRpcScreenshareRead                    OAuth2Scopes = "rpc.screenshare.read"
	OAuth2ScopesRpcScreenshareWrite                   OAuth2Scopes = "rpc.screenshare.write"
	OAuth2ScopesRpcActivitiesWrite                    OAuth2Scopes = "rpc.activities.write"
	OAuth2ScopesWebhookIncoming                       OAuth2Scopes = "webhook.incoming"
	OAuth2ScopesMessagesRead                          OAuth2Scopes = "messages.read"
	OAuth2ScopesApplicationsBuildsUpload              OAuth2Scopes = "applications.builds.upload"
	OAuth2ScopesApplicationsBuildsRead                OAuth2Scopes = "applications.builds.read"
	OAuth2ScopesApplicationsCommands                  OAuth2Scopes = "applications.commands"
	OAuth2ScopesApplicationsCommandsPermissionsUpdate OAuth2Scopes = "applications.commands.permissions.update"
	OAuth2ScopesApplicationsCommandsUpdate            OAuth2Scopes = "applications.commands.update"
	OAuth2ScopesApplicationsStoreUpdate               OAuth2Scopes = "applications.store.update"
	OAuth2ScopesApplicationsEntitlements              OAuth2Scopes = "applications.entitlements"
	OAuth2ScopesActivitiesRead                        OAuth2Scopes = "activities.read"
	OAuth2ScopesActivitiesWrite                       OAuth2Scopes = "activities.write"
	OAuth2ScopesActivitiesInvitesWrite                OAuth2Scopes = "activities.invites.write"
	OAuth2ScopesRelationshipsRead                     OAuth2Scopes = "relationships.read"
	OAuth2ScopesVoice                                 OAuth2Scopes = "voice"
	OAuth2ScopesDmChannelsRead                        OAuth2Scopes = "dm_channels.read"
	OAuth2ScopesRoleConnectionsWrite                  OAuth2Scopes = "role_connections.write"
	OAuth2ScopesOpenid                                OAuth2Scopes = "openid"
)
