// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// OnboardingPrompt
type OnboardingPrompt struct {
	ID           string `json:"id"`
	InOnboarding bool   `json:"in_onboarding"`
	Options      []any  `json:"options"`
	Required     bool   `json:"required"`
	SingleSelect bool   `json:"single_select"`
	Title        string `json:"title"`
	Type         int32  `json:"type"`
}

// OnboardingPromptOption
type OnboardingPromptOption struct {
	ID          string   `json:"id"`
	ChannelIds  []string `json:"channel_ids"`
	Description string   `json:"description"`
	Emoji       any      `json:"emoji"`
	RoleIds     []string `json:"role_ids"`
	Title       string   `json:"title"`
}

// OnboardingPromptOptionOptions
type OnboardingPromptOptionOptions struct {
	ID            any      `json:"id,omitempty"`
	ChannelIds    []string `json:"channel_ids,omitempty"`
	Description   *string  `json:"description,omitempty"`
	EmojiAnimated *bool    `json:"emoji_animated,omitempty"`
	EmojiID       any      `json:"emoji_id,omitempty"`
	EmojiName     *string  `json:"emoji_name,omitempty"`
	RoleIds       []string `json:"role_ids,omitempty"`
	Title         string   `json:"title"`
}

// OnboardingPromptType
type OnboardingPromptType int

const (
	OnboardingPromptType0 OnboardingPromptType = 0
	OnboardingPromptType1 OnboardingPromptType = 1
)
