// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// PartialDiscordIntegration
type PartialDiscordIntegration struct {
	ID            string  `json:"id"`
	Account       any     `json:"account"`
	ApplicationID string  `json:"application_id"`
	Name          *string `json:"name,omitempty"`
	Type          string  `json:"type"`
}

// PartialExternalConnectionIntegration
type PartialExternalConnectionIntegration struct {
	ID      string  `json:"id"`
	Account any     `json:"account"`
	Name    *string `json:"name,omitempty"`
	Type    string  `json:"type"`
}

// PartialGuildSubscriptionIntegration
type PartialGuildSubscriptionIntegration struct {
	ID      string  `json:"id"`
	Account any     `json:"account"`
	Name    *string `json:"name,omitempty"`
	Type    string  `json:"type"`
}
