// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// PinnedMessage
type PinnedMessage struct {
	Message  any       `json:"message"`
	PinnedAt time.Time `json:"pinned_at"`
}

// PinnedMessages
type PinnedMessages struct {
	HasMore bool  `json:"has_more"`
	Items   []any `json:"items"`
}
