// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// Poll
type Poll struct {
	AllowMultiselect bool      `json:"allow_multiselect"`
	Answers          []any     `json:"answers"`
	Expiry           time.Time `json:"expiry"`
	LayoutType       int32     `json:"layout_type"`
	Question         any       `json:"question"`
	Results          any       `json:"results"`
}

// PollAnswer
type PollAnswer struct {
	AnswerID  int32 `json:"answer_id"`
	PollMedia any   `json:"poll_media"`
}

// PollAnswerCreateOptions
type PollAnswerCreateOptions struct {
	PollMedia any `json:"poll_media"`
}

// PollAnswerDetails
type PollAnswerDetails struct {
	Users []any `json:"users"`
}

// PollCreateOptions
type PollCreateOptions struct {
	AllowMultiselect *bool  `json:"allow_multiselect,omitempty"`
	Answers          []any  `json:"answers"`
	Duration         *int32 `json:"duration,omitempty"`
	LayoutType       any    `json:"layout_type,omitempty"`
	Question         any    `json:"question"`
}

// PollEmoji
type PollEmoji struct {
	ID       any     `json:"id,omitempty"`
	Animated *bool   `json:"animated,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// PollEmojiCreateOptions
type PollEmojiCreateOptions struct {
	ID       any     `json:"id,omitempty"`
	Animated *bool   `json:"animated,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// PollLayoutTypes
type PollLayoutTypes struct {
}

// PollMedia
type PollMedia struct {
	Emoji any    `json:"emoji,omitempty"`
	Text  string `json:"text,omitempty"`
}

// PollMediaCreateOptions
type PollMediaCreateOptions struct {
	Emoji any     `json:"emoji,omitempty"`
	Text  *string `json:"text,omitempty"`
}

// PollResults
type PollResults struct {
	AnswerCounts []any `json:"answer_counts"`
	IsFinalized  bool  `json:"is_finalized"`
}

// PollResultsEntry
type PollResultsEntry struct {
	ID      int32 `json:"id"`
	Count   int32 `json:"count"`
	MeVoted bool  `json:"me_voted"`
}
