// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// PongInteractionCallbackOptions
type PongInteractionCallbackOptions struct {
	Type int32 `json:"type"`
}
