// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// PremiumGuildTiers
type PremiumGuildTiers int

const (
	PremiumGuildTiers0 PremiumGuildTiers = 0
	PremiumGuildTiers1 PremiumGuildTiers = 1
	PremiumGuildTiers2 PremiumGuildTiers = 2
	PremiumGuildTiers3 PremiumGuildTiers = 3
)

// PremiumTypes
type PremiumTypes int

const (
	PremiumTypes0 PremiumTypes = 0
	PremiumTypes1 PremiumTypes = 1
	PremiumTypes2 PremiumTypes = 2
	PremiumTypes3 PremiumTypes = 3
)
