// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// PrivateApplication
type PrivateApplication struct {
	ID                                string         `json:"id"`
	ApproximateGuildCount             *int32         `json:"approximate_guild_count,omitempty"`
	ApproximateUserAuthorizationCount int32          `json:"approximate_user_authorization_count"`
	ApproximateUserInstallCount       int32          `json:"approximate_user_install_count"`
	Bot                               any            `json:"bot,omitempty"`
	BotPublic                         bool           `json:"bot_public,omitempty"`
	BotRequireCodeGrant               bool           `json:"bot_require_code_grant,omitempty"`
	CoverImage                        string         `json:"cover_image,omitempty"`
	CustomInstallURL                  string         `json:"custom_install_url,omitempty"`
	Description                       string         `json:"description"`
	ExplicitContentFilter             int32          `json:"explicit_content_filter"`
	Flags                             int32          `json:"flags"`
	GuildID                           string         `json:"guild_id,omitempty"`
	Icon                              *string        `json:"icon,omitempty"`
	InstallParams                     any            `json:"install_params,omitempty"`
	IntegrationTypesConfig            map[string]any `json:"integration_types_config,omitempty"`
	InteractionsEndpointURL           *string        `json:"interactions_endpoint_url,omitempty"`
	MaxParticipants                   *int32         `json:"max_participants,omitempty"`
	Name                              string         `json:"name"`
	Owner                             any            `json:"owner"`
	PrimarySkuID                      string         `json:"primary_sku_id,omitempty"`
	PrivacyPolicyURL                  string         `json:"privacy_policy_url,omitempty"`
	RedirectUris                      []*string      `json:"redirect_uris"`
	RoleConnectionsVerificationURL    *string        `json:"role_connections_verification_url,omitempty"`
	RpcOrigins                        []*string      `json:"rpc_origins,omitempty"`
	Slug                              string         `json:"slug,omitempty"`
	Tags                              []string       `json:"tags,omitempty"`
	Team                              any            `json:"team,omitempty"`
	TermsOfServiceURL                 string         `json:"terms_of_service_url,omitempty"`
	Type                              any            `json:"type,omitempty"`
	VerifyKey                         string         `json:"verify_key"`
}

// PrivateChannel
type PrivateChannel struct {
	ID               string     `json:"id"`
	Flags            int32      `json:"flags"`
	LastMessageID    any        `json:"last_message_id,omitempty"`
	LastPinTimestamp *time.Time `json:"last_pin_timestamp,omitempty"`
	Recipients       []any      `json:"recipients"`
	Type             int32      `json:"type"`
}

// PrivateChannelLocation
type PrivateChannelLocation struct {
	ID        string `json:"id"`
	ChannelID string `json:"channel_id"`
	Kind      string `json:"kind"`
}

// PrivateGroupChannel
type PrivateGroupChannel struct {
	ID               string     `json:"id"`
	ApplicationID    string     `json:"application_id,omitempty"`
	Flags            int32      `json:"flags"`
	Icon             *string    `json:"icon,omitempty"`
	LastMessageID    any        `json:"last_message_id,omitempty"`
	LastPinTimestamp *time.Time `json:"last_pin_timestamp,omitempty"`
	Managed          bool       `json:"managed,omitempty"`
	Name             *string    `json:"name,omitempty"`
	OwnerID          string     `json:"owner_id"`
	Recipients       []any      `json:"recipients"`
	Type             int32      `json:"type"`
}

// PrivateGuildMember
type PrivateGuildMember struct {
	Avatar                     *string    `json:"avatar,omitempty"`
	AvatarDecorationData       any        `json:"avatar_decoration_data,omitempty"`
	Banner                     *string    `json:"banner,omitempty"`
	Collectibles               any        `json:"collectibles,omitempty"`
	CommunicationDisabledUntil *time.Time `json:"communication_disabled_until,omitempty"`
	Deaf                       bool       `json:"deaf"`
	Flags                      int32      `json:"flags"`
	JoinedAt                   time.Time  `json:"joined_at"`
	Mute                       bool       `json:"mute"`
	Nick                       *string    `json:"nick,omitempty"`
	Pending                    bool       `json:"pending"`
	Permissions                string     `json:"permissions,omitempty"`
	PremiumSince               *time.Time `json:"premium_since,omitempty"`
	Roles                      []string   `json:"roles"`
	User                       any        `json:"user"`
}
