// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// ProvisionalToken
type ProvisionalToken struct {
	AccessToken  string   `json:"access_token"`
	ExpiresAtS   *int32   `json:"expires_at_s,omitempty"`
	ExpiresIn    int32    `json:"expires_in"`
	IDToken      string   `json:"id_token"`
	RefreshToken *string  `json:"refresh_token,omitempty"`
	Scope        string   `json:"scope"`
	Scopes       []string `json:"scopes,omitempty"`
	TokenType    string   `json:"token_type"`
}
