// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// PruneGuildOptions
type PruneGuildOptions struct {
	ComputePruneCount *bool  `json:"compute_prune_count,omitempty"`
	Days              *int64 `json:"days,omitempty"`
	IncludeRoles      any    `json:"include_roles,omitempty"`
}
