// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// PurchaseNotification
type PurchaseNotification struct {
	GuildProductPurchase any   `json:"guild_product_purchase,omitempty"`
	Type                 int32 `json:"type"`
}

// PurchaseType
type PurchaseType int

const (
	PurchaseType0 PurchaseType = 0
)
