// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// Ratelimited Ratelimit error object returned by the Discord API
type RatelimitedResponse struct {
	Code       int64   `json:"code"`        // Discord internal error code. See error code reference
	Message    string  `json:"message"`     // Human-readable error message
	Global     bool    `json:"global"`      // Whether you are being ratelimited by the global ratelimit or a per-endpoint ratelimit
	RetryAfter float64 `json:"retry_after"` // The number of seconds to wait before retrying your request
}
