// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// ReactionTypes
type ReactionTypes int

const (
	ReactionTypes0 ReactionTypes = 0
	ReactionTypes1 ReactionTypes = 1
)
