// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// ResolvedObjects
type ResolvedObjects struct {
	Channels map[string]any `json:"channels,omitempty"`
	Members  map[string]any `json:"members,omitempty"`
	Roles    map[string]any `json:"roles,omitempty"`
	Users    map[string]any `json:"users,omitempty"`
}
