// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// ResourceChannel
type ResourceChannel struct {
	ChannelID   string `json:"channel_id"`
	Description string `json:"description"`
	Emoji       any    `json:"emoji,omitempty"`
	Icon        string `json:"icon,omitempty"`
	Title       string `json:"title"`
}
