// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// RichEmbed
type RichEmbed struct {
	Author      any        `json:"author,omitempty"`
	Color       *int64     `json:"color,omitempty"`
	Description *string    `json:"description,omitempty"`
	Fields      []any      `json:"fields,omitempty"`
	Footer      any        `json:"footer,omitempty"`
	Image       any        `json:"image,omitempty"`
	Provider    any        `json:"provider,omitempty"`
	Thumbnail   any        `json:"thumbnail,omitempty"`
	Timestamp   *time.Time `json:"timestamp,omitempty"`
	Title       *string    `json:"title,omitempty"`
	Type        *string    `json:"type,omitempty"`
	URL         *string    `json:"url,omitempty"`
	Video       any        `json:"video,omitempty"`
}

// RichEmbedAuthor
type RichEmbedAuthor struct {
	IconURL *string `json:"icon_url,omitempty"`
	Name    *string `json:"name,omitempty"`
	URL     *string `json:"url,omitempty"`
}

// RichEmbedField
type RichEmbedField struct {
	Inline *bool  `json:"inline,omitempty"`
	Name   string `json:"name"`
	Value  string `json:"value"`
}

// RichEmbedFooter
type RichEmbedFooter struct {
	IconURL *string `json:"icon_url,omitempty"`
	Text    *string `json:"text,omitempty"`
}

// RichEmbedImage
type RichEmbedImage struct {
	Description        *string `json:"description,omitempty"`
	Height             *int64  `json:"height,omitempty"`
	IsAnimated         *bool   `json:"is_animated,omitempty"`
	Placeholder        *string `json:"placeholder,omitempty"`
	PlaceholderVersion *int64  `json:"placeholder_version,omitempty"`
	URL                *string `json:"url,omitempty"`
	Width              *int64  `json:"width,omitempty"`
}

// RichEmbedProvider
type RichEmbedProvider struct {
	Name *string `json:"name,omitempty"`
	URL  *string `json:"url,omitempty"`
}

// RichEmbedThumbnail
type RichEmbedThumbnail struct {
	Description        *string `json:"description,omitempty"`
	Height             *int64  `json:"height,omitempty"`
	IsAnimated         *bool   `json:"is_animated,omitempty"`
	Placeholder        *string `json:"placeholder,omitempty"`
	PlaceholderVersion *int64  `json:"placeholder_version,omitempty"`
	URL                *string `json:"url,omitempty"`
	Width              *int64  `json:"width,omitempty"`
}

// RichEmbedVideo
type RichEmbedVideo struct {
	Description        *string `json:"description,omitempty"`
	Height             *int64  `json:"height,omitempty"`
	IsAnimated         *bool   `json:"is_animated,omitempty"`
	Placeholder        *string `json:"placeholder,omitempty"`
	PlaceholderVersion *int64  `json:"placeholder_version,omitempty"`
	URL                *string `json:"url,omitempty"`
	Width              *int64  `json:"width,omitempty"`
}
