// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// ScheduledEvent
type ScheduledEvent struct {
	ID                 string     `json:"id"`
	ChannelID          any        `json:"channel_id,omitempty"`
	Creator            any        `json:"creator,omitempty"`
	CreatorID          any        `json:"creator_id,omitempty"`
	Description        *string    `json:"description,omitempty"`
	EntityID           any        `json:"entity_id,omitempty"`
	EntityType         int32      `json:"entity_type"`
	GuildID            string     `json:"guild_id"`
	Image              *string    `json:"image,omitempty"`
	Name               string     `json:"name"`
	PrivacyLevel       int32      `json:"privacy_level"`
	ScheduledEndTime   *time.Time `json:"scheduled_end_time,omitempty"`
	ScheduledStartTime time.Time  `json:"scheduled_start_time"`
	Status             int32      `json:"status"`
	UserCount          int32      `json:"user_count,omitempty"`
	UserRsvp           any        `json:"user_rsvp,omitempty"`
}

// ScheduledEventUser
type ScheduledEventUser struct {
	GuildScheduledEventID string `json:"guild_scheduled_event_id"`
	Member                any    `json:"member,omitempty"`
	User                  any    `json:"user,omitempty"`
	UserID                string `json:"user_id"`
}
