// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// SectionComponent
type SectionComponent struct {
	ID         int32 `json:"id"`
	Accessory  any   `json:"accessory"`
	Components []any `json:"components"`
	Type       int32 `json:"type"`
}

// SectionComponentForMessageOptions
type SectionComponentForMessageOptions struct {
	ID         *int32 `json:"id,omitempty"`
	Accessory  any    `json:"accessory"`
	Components []any  `json:"components"`
	Type       int32  `json:"type"`
}
