// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// SeparatorComponent
type SeparatorComponent struct {
	ID      int32 `json:"id"`
	Divider bool  `json:"divider"`
	Spacing int32 `json:"spacing"`
	Type    int32 `json:"type"`
}

// SeparatorComponentForMessageOptions
type SeparatorComponentForMessageOptions struct {
	ID      *int32 `json:"id,omitempty"`
	Divider *bool  `json:"divider,omitempty"`
	Spacing any    `json:"spacing,omitempty"`
	Type    int32  `json:"type"`
}
