// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// SettingsEmoji
type SettingsEmoji struct {
	ID       any     `json:"id,omitempty"`
	Animated bool    `json:"animated"`
	Name     *string `json:"name,omitempty"`
}
