// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// SlackWebhook
type SlackWebhook struct {
	Attachments []any   `json:"attachments,omitempty"`
	IconURL     *string `json:"icon_url,omitempty"`
	Text        *string `json:"text,omitempty"`
	Username    *string `json:"username,omitempty"`
}
