// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// SnowflakeSelectDefaultValueTypes
type SnowflakeSelectDefaultValueTypes string

const (
	SnowflakeSelectDefaultValueTypesUser    SnowflakeSelectDefaultValueTypes = "user"
	SnowflakeSelectDefaultValueTypesRole    SnowflakeSelectDefaultValueTypes = "role"
	SnowflakeSelectDefaultValueTypesChannel SnowflakeSelectDefaultValueTypes = "channel"
)

// SnowflakeType is a Discord snowflake ID (just a string).
type SnowflakeType = string
