// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"github.com/kolosys/discord/types"
)

// SnowflakeSelectDefaultValueTypes
type SnowflakeSelectDefaultValueTypes string

const (
	SnowflakeSelectDefaultValueTypesUser    SnowflakeSelectDefaultValueTypes = "user"
	SnowflakeSelectDefaultValueTypesRole    SnowflakeSelectDefaultValueTypes = "role"
	SnowflakeSelectDefaultValueTypesChannel SnowflakeSelectDefaultValueTypes = "channel"
)

// SnowflakeType is a Discord snowflake ID used in API requests.
// It implements fmt.Stringer for use in path parameters.
type SnowflakeType = types.Snowflake
