// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// SortingOrder
type SortingOrder string

const (
	SortingOrderAsc  SortingOrder = "asc"
	SortingOrderDesc SortingOrder = "desc"
)
