// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// SoundboardCreateOptions
type SoundboardCreateOptions struct {
	EmojiID   any      `json:"emoji_id,omitempty"`
	EmojiName *string  `json:"emoji_name,omitempty"`
	Name      string   `json:"name"`
	Sound     string   `json:"sound"`
	Volume    *float64 `json:"volume,omitempty"`
}

// SoundboardPatchOptionsPartial
type SoundboardPatchOptionsPartial struct {
	EmojiID   any      `json:"emoji_id,omitempty"`
	EmojiName *string  `json:"emoji_name,omitempty"`
	Name      string   `json:"name,omitempty"`
	Volume    *float64 `json:"volume,omitempty"`
}

// SoundboardSound
type SoundboardSound struct {
	Available bool    `json:"available"`
	EmojiID   any     `json:"emoji_id,omitempty"`
	EmojiName *string `json:"emoji_name,omitempty"`
	GuildID   string  `json:"guild_id,omitempty"`
	Name      string  `json:"name"`
	SoundID   string  `json:"sound_id"`
	User      any     `json:"user,omitempty"`
	Volume    float64 `json:"volume"`
}

// SoundboardSoundSendOptions
type SoundboardSoundSendOptions struct {
	SoundID       string `json:"sound_id"`
	SourceGuildID any    `json:"source_guild_id,omitempty"`
}
