// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// SpamLinkRule
type SpamLinkRule struct {
	ID              string   `json:"id"`
	Actions         []any    `json:"actions"`
	CreatorID       string   `json:"creator_id"`
	Enabled         bool     `json:"enabled"`
	EventType       int32    `json:"event_type"`
	ExemptChannels  []string `json:"exempt_channels"`
	ExemptRoles     []string `json:"exempt_roles"`
	GuildID         string   `json:"guild_id"`
	Name            string   `json:"name"`
	TriggerMetadata any      `json:"trigger_metadata"`
	TriggerType     int32    `json:"trigger_type"`
}

// SpamLinkTriggerMetadata
type SpamLinkTriggerMetadata struct {
}
