// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// StageInstance
type StageInstance struct {
	ID                    string `json:"id"`
	ChannelID             string `json:"channel_id"`
	DiscoverableDisabled  bool   `json:"discoverable_disabled"`
	GuildID               string `json:"guild_id"`
	GuildScheduledEventID any    `json:"guild_scheduled_event_id,omitempty"`
	PrivacyLevel          int32  `json:"privacy_level"`
	Topic                 string `json:"topic"`
}

// StageInstancesPrivacyLevels
type StageInstancesPrivacyLevels int

const (
	StageInstancesPrivacyLevels1 StageInstancesPrivacyLevels = 1
	StageInstancesPrivacyLevels2 StageInstancesPrivacyLevels = 2
)

// StageScheduledEvent
type StageScheduledEvent struct {
	ID                 string     `json:"id"`
	ChannelID          any        `json:"channel_id,omitempty"`
	Creator            any        `json:"creator,omitempty"`
	CreatorID          any        `json:"creator_id,omitempty"`
	Description        *string    `json:"description,omitempty"`
	EntityID           any        `json:"entity_id,omitempty"`
	EntityMetadata     any        `json:"entity_metadata,omitempty"`
	EntityType         int32      `json:"entity_type"`
	GuildID            string     `json:"guild_id"`
	Image              *string    `json:"image,omitempty"`
	Name               string     `json:"name"`
	PrivacyLevel       int32      `json:"privacy_level"`
	ScheduledEndTime   *time.Time `json:"scheduled_end_time,omitempty"`
	ScheduledStartTime time.Time  `json:"scheduled_start_time"`
	Status             int32      `json:"status"`
	UserCount          int32      `json:"user_count,omitempty"`
	UserRsvp           any        `json:"user_rsvp,omitempty"`
}

// StageScheduledEventCreateOptions
type StageScheduledEventCreateOptions struct {
	ChannelID          any        `json:"channel_id,omitempty"`
	Description        *string    `json:"description,omitempty"`
	EntityMetadata     any        `json:"entity_metadata,omitempty"`
	EntityType         int32      `json:"entity_type"`
	Image              *string    `json:"image,omitempty"`
	Name               string     `json:"name"`
	PrivacyLevel       int32      `json:"privacy_level"`
	ScheduledEndTime   *time.Time `json:"scheduled_end_time,omitempty"`
	ScheduledStartTime time.Time  `json:"scheduled_start_time"`
}

// StageScheduledEventPatchOptionsPartial
type StageScheduledEventPatchOptionsPartial struct {
	ChannelID          any        `json:"channel_id,omitempty"`
	Description        *string    `json:"description,omitempty"`
	EntityMetadata     any        `json:"entity_metadata,omitempty"`
	EntityType         any        `json:"entity_type,omitempty"`
	Image              *string    `json:"image,omitempty"`
	Name               string     `json:"name,omitempty"`
	PrivacyLevel       int32      `json:"privacy_level,omitempty"`
	ScheduledEndTime   *time.Time `json:"scheduled_end_time,omitempty"`
	ScheduledStartTime time.Time  `json:"scheduled_start_time,omitempty"`
	Status             any        `json:"status,omitempty"`
}
