// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// StandardSticker
type StandardSticker struct {
	ID          string  `json:"id"`
	Description *string `json:"description,omitempty"`
	FormatType  any     `json:"format_type,omitempty"`
	Name        string  `json:"name"`
	PackID      string  `json:"pack_id"`
	SortValue   int32   `json:"sort_value"`
	Tags        string  `json:"tags"`
	Type        int32   `json:"type"`
}
