// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// StickerFormatTypes
type StickerFormatTypes int

const (
	StickerFormatTypes1 StickerFormatTypes = 1
	StickerFormatTypes2 StickerFormatTypes = 2
	StickerFormatTypes3 StickerFormatTypes = 3
	StickerFormatTypes4 StickerFormatTypes = 4
)

// StickerPack
type StickerPack struct {
	ID             string  `json:"id"`
	BannerAssetID  string  `json:"banner_asset_id,omitempty"`
	CoverStickerID string  `json:"cover_sticker_id,omitempty"`
	Description    *string `json:"description,omitempty"`
	Name           string  `json:"name"`
	SkuID          string  `json:"sku_id"`
	Stickers       []any   `json:"stickers"`
}

// StickerPackCollection
type StickerPackCollection struct {
	StickerPacks []any `json:"sticker_packs"`
}

// StickerTypes
type StickerTypes int

const (
	StickerTypes1 StickerTypes = 1
	StickerTypes2 StickerTypes = 2
)
