// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// StringSelectComponent
type StringSelectComponent struct {
	ID          int32  `json:"id"`
	CustomID    string `json:"custom_id"`
	Disabled    bool   `json:"disabled,omitempty"`
	MaxValues   *int32 `json:"max_values,omitempty"`
	MinValues   *int32 `json:"min_values,omitempty"`
	Options     []any  `json:"options"`
	Placeholder string `json:"placeholder,omitempty"`
	Type        int32  `json:"type"`
}

// StringSelectComponentForMessageOptions
type StringSelectComponentForMessageOptions struct {
	ID          *int32  `json:"id,omitempty"`
	CustomID    string  `json:"custom_id"`
	Disabled    *bool   `json:"disabled,omitempty"`
	MaxValues   *int64  `json:"max_values,omitempty"`
	MinValues   *int64  `json:"min_values,omitempty"`
	Options     []any   `json:"options"`
	Placeholder *string `json:"placeholder,omitempty"`
	Required    *bool   `json:"required,omitempty"`
	Type        int32   `json:"type"`
}

// StringSelectComponentForModalOptions
type StringSelectComponentForModalOptions struct {
	ID          *int32  `json:"id,omitempty"`
	CustomID    string  `json:"custom_id"`
	Disabled    *bool   `json:"disabled,omitempty"`
	MaxValues   *int64  `json:"max_values,omitempty"`
	MinValues   *int64  `json:"min_values,omitempty"`
	Options     []any   `json:"options"`
	Placeholder *string `json:"placeholder,omitempty"`
	Required    *bool   `json:"required,omitempty"`
	Type        int32   `json:"type"`
}

// StringSelectOption
type StringSelectOption struct {
	Default     bool   `json:"default,omitempty"`
	Description string `json:"description,omitempty"`
	Emoji       any    `json:"emoji,omitempty"`
	Label       string `json:"label"`
	Value       string `json:"value"`
}

// StringSelectOptionForOptions
type StringSelectOptionForOptions struct {
	Default     *bool   `json:"default,omitempty"`
	Description *string `json:"description,omitempty"`
	Emoji       any     `json:"emoji,omitempty"`
	Label       string  `json:"label"`
	Value       string  `json:"value"`
}
