// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// Team
type Team struct {
	ID          string  `json:"id"`
	Icon        *string `json:"icon,omitempty"`
	Members     []any   `json:"members"`
	Name        string  `json:"name"`
	OwnerUserID string  `json:"owner_user_id"`
}

// TeamMember
type TeamMember struct {
	MembershipState int32  `json:"membership_state"`
	TeamID          string `json:"team_id"`
	User            any    `json:"user"`
}

// TeamMembershipStates
type TeamMembershipStates int

const (
	TeamMembershipStates1 TeamMembershipStates = 1
	TeamMembershipStates2 TeamMembershipStates = 2
)
