// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// TextDisplayComponent
type TextDisplayComponent struct {
	ID      int32  `json:"id"`
	Content string `json:"content"`
	Type    int32  `json:"type"`
}

// TextDisplayComponentForMessageOptions
type TextDisplayComponentForMessageOptions struct {
	ID      *int32 `json:"id,omitempty"`
	Content string `json:"content"`
	Type    int32  `json:"type"`
}

// TextDisplayComponentForModalOptions
type TextDisplayComponentForModalOptions struct {
	ID      *int32 `json:"id,omitempty"`
	Content string `json:"content"`
	Type    int32  `json:"type"`
}

// TextInputComponent
type TextInputComponent struct {
	ID          int32   `json:"id"`
	CustomID    string  `json:"custom_id"`
	Label       *string `json:"label,omitempty"`
	MaxLength   *int32  `json:"max_length,omitempty"`
	MinLength   *int32  `json:"min_length,omitempty"`
	Placeholder string  `json:"placeholder,omitempty"`
	Required    bool    `json:"required,omitempty"`
	Style       int32   `json:"style"`
	Type        int32   `json:"type"`
	Value       string  `json:"value,omitempty"`
}

// TextInputComponentForModalOptions
type TextInputComponentForModalOptions struct {
	ID          *int32  `json:"id,omitempty"`
	CustomID    string  `json:"custom_id"`
	Label       *string `json:"label,omitempty"`
	MaxLength   *int64  `json:"max_length,omitempty"`
	MinLength   *int64  `json:"min_length,omitempty"`
	Placeholder *string `json:"placeholder,omitempty"`
	Required    *bool   `json:"required,omitempty"`
	Style       int32   `json:"style"`
	Type        int32   `json:"type"`
	Value       *string `json:"value,omitempty"`
}

// TextInputStyleTypes
type TextInputStyleTypes int

const (
	TextInputStyleTypes1 TextInputStyleTypes = 1
	TextInputStyleTypes2 TextInputStyleTypes = 2
)
