// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// Threads
type Threads struct {
	FirstMessages []any `json:"first_messages,omitempty"`
	HasMore       bool  `json:"has_more"`
	Members       []any `json:"members"`
	Threads       []any `json:"threads"`
}
