// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// Thread
type Thread struct {
	ID               string     `json:"id"`
	AppliedTags      []string   `json:"applied_tags,omitempty"`
	Bitrate          int32      `json:"bitrate,omitempty"`
	Flags            int32      `json:"flags"`
	GuildID          string     `json:"guild_id"`
	LastMessageID    any        `json:"last_message_id,omitempty"`
	LastPinTimestamp *time.Time `json:"last_pin_timestamp,omitempty"`
	Member           any        `json:"member,omitempty"`
	MemberCount      int32      `json:"member_count"`
	MessageCount     int32      `json:"message_count"`
	Name             string     `json:"name"`
	OwnerID          string     `json:"owner_id"`
	ParentID         any        `json:"parent_id,omitempty"`
	Permissions      *string    `json:"permissions,omitempty"`
	RateLimitPerUser int32      `json:"rate_limit_per_user,omitempty"`
	RtcRegion        *string    `json:"rtc_region,omitempty"`
	ThreadMetadata   any        `json:"thread_metadata"`
	TotalMessageSent int32      `json:"total_message_sent"`
	Type             int32      `json:"type"`
	UserLimit        int32      `json:"user_limit,omitempty"`
	VideoQualityMode int32      `json:"video_quality_mode,omitempty"`
}

// ThreadAutoArchiveDuration
type ThreadAutoArchiveDuration int

const (
	ThreadAutoArchiveDuration60    ThreadAutoArchiveDuration = 60
	ThreadAutoArchiveDuration1440  ThreadAutoArchiveDuration = 1440
	ThreadAutoArchiveDuration4320  ThreadAutoArchiveDuration = 4320
	ThreadAutoArchiveDuration10080 ThreadAutoArchiveDuration = 10080
)

// ThreadMember
type ThreadMember struct {
	ID            string    `json:"id"`
	Flags         int32     `json:"flags"`
	JoinTimestamp time.Time `json:"join_timestamp"`
	Member        any       `json:"member,omitempty"`
	UserID        string    `json:"user_id"`
}

// ThreadMetadata
type ThreadMetadata struct {
	ArchiveTimestamp    *time.Time `json:"archive_timestamp,omitempty"`
	Archived            bool       `json:"archived"`
	AutoArchiveDuration int32      `json:"auto_archive_duration"`
	CreateTimestamp     time.Time  `json:"create_timestamp,omitempty"`
	Invitable           bool       `json:"invitable,omitempty"`
	Locked              bool       `json:"locked"`
}

// ThreadSearch
type ThreadSearch struct {
	FirstMessages []any `json:"first_messages,omitempty"`
	HasMore       bool  `json:"has_more"`
	Members       []any `json:"members"`
	Threads       []any `json:"threads"`
	TotalResults  int32 `json:"total_results"`
}

// ThreadSearchTagSetting
type ThreadSearchTagSetting string

const (
	ThreadSearchTagSettingMatchAll  ThreadSearchTagSetting = "match_all"
	ThreadSearchTagSettingMatchSome ThreadSearchTagSetting = "match_some"
)

// ThreadSortOrder
type ThreadSortOrder int

const (
	ThreadSortOrder0 ThreadSortOrder = 0
	ThreadSortOrder1 ThreadSortOrder = 1
)

// ThreadSortingMode
type ThreadSortingMode string

const (
	ThreadSortingModeRelevance       ThreadSortingMode = "relevance"
	ThreadSortingModeCreationTime    ThreadSortingMode = "creation_time"
	ThreadSortingModeLastMessageTime ThreadSortingMode = "last_message_time"
	ThreadSortingModeArchiveTime     ThreadSortingMode = "archive_time"
)
