// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// ThumbnailComponent
type ThumbnailComponent struct {
	ID          int32   `json:"id"`
	Description *string `json:"description,omitempty"`
	Media       any     `json:"media"`
	Spoiler     bool    `json:"spoiler"`
	Type        int32   `json:"type"`
}

// ThumbnailComponentForMessageOptions
type ThumbnailComponentForMessageOptions struct {
	ID          *int32  `json:"id,omitempty"`
	Description *string `json:"description,omitempty"`
	Media       any     `json:"media"`
	Spoiler     *bool   `json:"spoiler,omitempty"`
	Type        int32   `json:"type"`
}
