// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// UnfurledMedia
type UnfurledMedia struct {
	ID           string  `json:"id"`
	AttachmentID string  `json:"attachment_id,omitempty"`
	ContentType  *string `json:"content_type,omitempty"`
	Height       *int32  `json:"height,omitempty"`
	ProxyURL     string  `json:"proxy_url"`
	URL          string  `json:"url"`
	Width        *int32  `json:"width,omitempty"`
}

// UnfurledMediaOptions
type UnfurledMediaOptions struct {
	URL string `json:"url"`
}

// UnfurledMediaOptionsWithAttachmentReferenceRequired
type UnfurledMediaOptionsWithAttachmentReferenceRequired struct {
	URL string `json:"url"`
}
