// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// UpdateApplicationUserRoleConnectionOptions
type UpdateApplicationUserRoleConnectionOptions struct {
	Metadata         map[string]string `json:"metadata,omitempty"`
	PlatformName     *string           `json:"platform_name,omitempty"`
	PlatformUsername *string           `json:"platform_username,omitempty"`
}

// UpdateDMOptionsPartial
type UpdateDMOptionsPartial struct {
	Name *string `json:"name,omitempty"`
}

// UpdateDefaultReactionEmojiOptions
type UpdateDefaultReactionEmojiOptions struct {
	EmojiID   any     `json:"emoji_id,omitempty"`
	EmojiName *string `json:"emoji_name,omitempty"`
}

// UpdateGroupDMOptionsPartial
type UpdateGroupDMOptionsPartial struct {
	Icon *string `json:"icon,omitempty"`
	Name *string `json:"name,omitempty"`
}

// UpdateGuildChannelOptionsPartial
type UpdateGuildChannelOptionsPartial struct {
	AvailableTags                 []any   `json:"available_tags,omitempty"`
	Bitrate                       *int32  `json:"bitrate,omitempty"`
	DefaultAutoArchiveDuration    any     `json:"default_auto_archive_duration,omitempty"`
	DefaultForumLayout            any     `json:"default_forum_layout,omitempty"`
	DefaultReactionEmoji          any     `json:"default_reaction_emoji,omitempty"`
	DefaultSortOrder              any     `json:"default_sort_order,omitempty"`
	DefaultTagSetting             any     `json:"default_tag_setting,omitempty"`
	DefaultThreadRateLimitPerUser *int64  `json:"default_thread_rate_limit_per_user,omitempty"`
	Flags                         *int64  `json:"flags,omitempty"`
	Name                          string  `json:"name,omitempty"`
	Nsfw                          *bool   `json:"nsfw,omitempty"`
	ParentID                      any     `json:"parent_id,omitempty"`
	PermissionOverwrites          []any   `json:"permission_overwrites,omitempty"`
	Position                      *int32  `json:"position,omitempty"`
	RateLimitPerUser              *int64  `json:"rate_limit_per_user,omitempty"`
	RtcRegion                     *string `json:"rtc_region,omitempty"`
	Topic                         *string `json:"topic,omitempty"`
	Type                          any     `json:"type,omitempty"`
	UserLimit                     *int32  `json:"user_limit,omitempty"`
	VideoQualityMode              any     `json:"video_quality_mode,omitempty"`
}

// UpdateGuildOnboardingOptions
type UpdateGuildOnboardingOptions struct {
	DefaultChannelIds []string `json:"default_channel_ids,omitempty"`
	Enabled           *bool    `json:"enabled,omitempty"`
	Mode              any      `json:"mode,omitempty"`
	Prompts           []any    `json:"prompts,omitempty"`
}

// UpdateMessageInteractionCallback
type UpdateMessageInteractionCallback struct {
	Message any   `json:"message"`
	Type    int32 `json:"type"`
}

// UpdateMessageInteractionCallbackOptions
type UpdateMessageInteractionCallbackOptions struct {
	Data any   `json:"data,omitempty"`
	Type int32 `json:"type"`
}

// UpdateOnboardingPromptOptions
type UpdateOnboardingPromptOptions struct {
	ID           string `json:"id"`
	InOnboarding *bool  `json:"in_onboarding,omitempty"`
	Options      []any  `json:"options"`
	Required     *bool  `json:"required,omitempty"`
	SingleSelect *bool  `json:"single_select,omitempty"`
	Title        string `json:"title"`
	Type         any    `json:"type,omitempty"`
}

// UpdateRoleOptionsPartial
type UpdateRoleOptionsPartial struct {
	Color        *int64  `json:"color,omitempty"`
	Hoist        *bool   `json:"hoist,omitempty"`
	Icon         *string `json:"icon,omitempty"`
	Mentionable  *bool   `json:"mentionable,omitempty"`
	Name         *string `json:"name,omitempty"`
	Permissions  *int64  `json:"permissions,omitempty"`
	UnicodeEmoji *string `json:"unicode_emoji,omitempty"`
}

// UpdateRolePositionsOptions
type UpdateRolePositionsOptions struct {
	ID       any    `json:"id,omitempty"`
	Position *int32 `json:"position,omitempty"`
}

// UpdateSelfVoiceStateOptionsPartial
type UpdateSelfVoiceStateOptionsPartial struct {
	ChannelID               any        `json:"channel_id,omitempty"`
	RequestToSpeakTimestamp *time.Time `json:"request_to_speak_timestamp,omitempty"`
	Suppress                *bool      `json:"suppress,omitempty"`
}

// UpdateThreadOptionsPartial
type UpdateThreadOptionsPartial struct {
	AppliedTags         []string `json:"applied_tags,omitempty"`
	Archived            *bool    `json:"archived,omitempty"`
	AutoArchiveDuration any      `json:"auto_archive_duration,omitempty"`
	Bitrate             *int32   `json:"bitrate,omitempty"`
	Flags               *int64   `json:"flags,omitempty"`
	Invitable           *bool    `json:"invitable,omitempty"`
	Locked              *bool    `json:"locked,omitempty"`
	Name                *string  `json:"name,omitempty"`
	RateLimitPerUser    *int64   `json:"rate_limit_per_user,omitempty"`
	RtcRegion           *string  `json:"rtc_region,omitempty"`
	UserLimit           *int64   `json:"user_limit,omitempty"`
	VideoQualityMode    any      `json:"video_quality_mode,omitempty"`
}

// UpdateThreadTagOptions
type UpdateThreadTagOptions struct {
	ID        any     `json:"id,omitempty"`
	EmojiID   any     `json:"emoji_id,omitempty"`
	EmojiName *string `json:"emoji_name,omitempty"`
	Moderated *bool   `json:"moderated,omitempty"`
	Name      string  `json:"name"`
}

// UpdateVoiceStateOptionsPartial
type UpdateVoiceStateOptionsPartial struct {
	ChannelID any   `json:"channel_id,omitempty"`
	Suppress  *bool `json:"suppress,omitempty"`
}
