// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// User
type User struct {
	ID                   string  `json:"id"`
	AccentColor          *int32  `json:"accent_color,omitempty"`
	Avatar               *string `json:"avatar,omitempty"`
	AvatarDecorationData any     `json:"avatar_decoration_data,omitempty"`
	Banner               *string `json:"banner,omitempty"`
	Bot                  bool    `json:"bot,omitempty"`
	Collectibles         any     `json:"collectibles,omitempty"`
	Discriminator        string  `json:"discriminator"`
	Flags                int64   `json:"flags"`
	GlobalName           *string `json:"global_name,omitempty"`
	PrimaryGuild         any     `json:"primary_guild,omitempty"`
	PublicFlags          int32   `json:"public_flags"`
	System               bool    `json:"system,omitempty"`
	Username             string  `json:"username"`
}

// UserAvatarDecoration
type UserAvatarDecoration struct {
	Asset string `json:"asset"`
	SkuID any    `json:"sku_id,omitempty"`
}

// UserCollectibles
type UserCollectibles struct {
	Nameplate any `json:"nameplate,omitempty"`
}

// UserCommunicationDisabledAction
type UserCommunicationDisabledAction struct {
	Metadata any   `json:"metadata"`
	Type     int32 `json:"type"`
}

// UserCommunicationDisabledActionMetadata
type UserCommunicationDisabledActionMetadata struct {
	DurationSeconds int32 `json:"duration_seconds"`
}

// UserGuildOnboarding
type UserGuildOnboarding struct {
	DefaultChannelIds []string `json:"default_channel_ids"`
	Enabled           bool     `json:"enabled"`
	GuildID           string   `json:"guild_id"`
	Prompts           []any    `json:"prompts"`
}

// UserNameplate
type UserNameplate struct {
	Asset   string `json:"asset"`
	Label   string `json:"label"`
	Palette string `json:"palette"`
	SkuID   any    `json:"sku_id,omitempty"`
}

// UserNotificationSettings
type UserNotificationSettings int

const (
	UserNotificationSettings0 UserNotificationSettings = 0
	UserNotificationSettings1 UserNotificationSettings = 1
)

// UserPII
type UserPII struct {
	ID                   string  `json:"id"`
	AccentColor          *int32  `json:"accent_color,omitempty"`
	Avatar               *string `json:"avatar,omitempty"`
	AvatarDecorationData any     `json:"avatar_decoration_data,omitempty"`
	Banner               *string `json:"banner,omitempty"`
	Bot                  bool    `json:"bot,omitempty"`
	Collectibles         any     `json:"collectibles,omitempty"`
	Discriminator        string  `json:"discriminator"`
	Email                *string `json:"email,omitempty"`
	Flags                int64   `json:"flags"`
	GlobalName           *string `json:"global_name,omitempty"`
	Locale               string  `json:"locale"`
	MfaEnabled           bool    `json:"mfa_enabled"`
	PremiumType          int32   `json:"premium_type,omitempty"`
	PrimaryGuild         any     `json:"primary_guild,omitempty"`
	PublicFlags          int32   `json:"public_flags"`
	System               bool    `json:"system,omitempty"`
	Username             string  `json:"username"`
	Verified             bool    `json:"verified,omitempty"`
}

// UserPrimaryGuild
type UserPrimaryGuild struct {
	Badge           *string `json:"badge,omitempty"`
	IdentityEnabled *bool   `json:"identity_enabled,omitempty"`
	IdentityGuildID any     `json:"identity_guild_id,omitempty"`
	Tag             *string `json:"tag,omitempty"`
}

// UserSelectComponent
type UserSelectComponent struct {
	ID            int32  `json:"id"`
	CustomID      string `json:"custom_id"`
	DefaultValues []any  `json:"default_values,omitempty"`
	Disabled      bool   `json:"disabled,omitempty"`
	MaxValues     *int32 `json:"max_values,omitempty"`
	MinValues     *int32 `json:"min_values,omitempty"`
	Placeholder   string `json:"placeholder,omitempty"`
	Type          int32  `json:"type"`
}

// UserSelectComponentForMessageOptions
type UserSelectComponentForMessageOptions struct {
	ID            *int32  `json:"id,omitempty"`
	CustomID      string  `json:"custom_id"`
	DefaultValues []any   `json:"default_values,omitempty"`
	Disabled      *bool   `json:"disabled,omitempty"`
	MaxValues     *int64  `json:"max_values,omitempty"`
	MinValues     *int64  `json:"min_values,omitempty"`
	Placeholder   *string `json:"placeholder,omitempty"`
	Required      *bool   `json:"required,omitempty"`
	Type          int32   `json:"type"`
}

// UserSelectComponentForModalOptions
type UserSelectComponentForModalOptions struct {
	ID            *int32  `json:"id,omitempty"`
	CustomID      string  `json:"custom_id"`
	DefaultValues []any   `json:"default_values,omitempty"`
	Disabled      *bool   `json:"disabled,omitempty"`
	MaxValues     *int64  `json:"max_values,omitempty"`
	MinValues     *int64  `json:"min_values,omitempty"`
	Placeholder   *string `json:"placeholder,omitempty"`
	Required      *bool   `json:"required,omitempty"`
	Type          int32   `json:"type"`
}

// UserSelectDefaultValue
type UserSelectDefaultValue struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}
