// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// VanityURL
type VanityURL struct {
	Code  *string `json:"code,omitempty"`
	Error any     `json:"error,omitempty"`
	Uses  int32   `json:"uses"`
}

// VanityURLError
type VanityURLError struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}
