// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// VerificationLevels
type VerificationLevels int

const (
	VerificationLevels0 VerificationLevels = 0
	VerificationLevels1 VerificationLevels = 1
	VerificationLevels2 VerificationLevels = 2
	VerificationLevels3 VerificationLevels = 3
	VerificationLevels4 VerificationLevels = 4
)
