// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// VideoQualityModes
type VideoQualityModes int

const (
	VideoQualityModes1 VideoQualityModes = 1
	VideoQualityModes2 VideoQualityModes = 2
)
