// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

import (
	"time"
)

// VoiceRegion
type VoiceRegion struct {
	ID         string `json:"id"`
	Custom     bool   `json:"custom"`
	Deprecated bool   `json:"deprecated"`
	Name       string `json:"name"`
	Optimal    bool   `json:"optimal"`
}

// VoiceScheduledEvent
type VoiceScheduledEvent struct {
	ID                 string     `json:"id"`
	ChannelID          any        `json:"channel_id,omitempty"`
	Creator            any        `json:"creator,omitempty"`
	CreatorID          any        `json:"creator_id,omitempty"`
	Description        *string    `json:"description,omitempty"`
	EntityID           any        `json:"entity_id,omitempty"`
	EntityMetadata     any        `json:"entity_metadata,omitempty"`
	EntityType         int32      `json:"entity_type"`
	GuildID            string     `json:"guild_id"`
	Image              *string    `json:"image,omitempty"`
	Name               string     `json:"name"`
	PrivacyLevel       int32      `json:"privacy_level"`
	ScheduledEndTime   *time.Time `json:"scheduled_end_time,omitempty"`
	ScheduledStartTime time.Time  `json:"scheduled_start_time"`
	Status             int32      `json:"status"`
	UserCount          int32      `json:"user_count,omitempty"`
	UserRsvp           any        `json:"user_rsvp,omitempty"`
}

// VoiceScheduledEventCreateOptions
type VoiceScheduledEventCreateOptions struct {
	ChannelID          any        `json:"channel_id,omitempty"`
	Description        *string    `json:"description,omitempty"`
	EntityMetadata     any        `json:"entity_metadata,omitempty"`
	EntityType         int32      `json:"entity_type"`
	Image              *string    `json:"image,omitempty"`
	Name               string     `json:"name"`
	PrivacyLevel       int32      `json:"privacy_level"`
	ScheduledEndTime   *time.Time `json:"scheduled_end_time,omitempty"`
	ScheduledStartTime time.Time  `json:"scheduled_start_time"`
}

// VoiceScheduledEventPatchOptionsPartial
type VoiceScheduledEventPatchOptionsPartial struct {
	ChannelID          any        `json:"channel_id,omitempty"`
	Description        *string    `json:"description,omitempty"`
	EntityMetadata     any        `json:"entity_metadata,omitempty"`
	EntityType         any        `json:"entity_type,omitempty"`
	Image              *string    `json:"image,omitempty"`
	Name               string     `json:"name,omitempty"`
	PrivacyLevel       int32      `json:"privacy_level,omitempty"`
	ScheduledEndTime   *time.Time `json:"scheduled_end_time,omitempty"`
	ScheduledStartTime time.Time  `json:"scheduled_start_time,omitempty"`
	Status             any        `json:"status,omitempty"`
}

// VoiceState
type VoiceState struct {
	ChannelID               any        `json:"channel_id,omitempty"`
	Deaf                    bool       `json:"deaf"`
	GuildID                 any        `json:"guild_id,omitempty"`
	Member                  any        `json:"member,omitempty"`
	Mute                    bool       `json:"mute"`
	RequestToSpeakTimestamp *time.Time `json:"request_to_speak_timestamp,omitempty"`
	SelfDeaf                bool       `json:"self_deaf"`
	SelfMute                bool       `json:"self_mute"`
	SelfStream              *bool      `json:"self_stream,omitempty"`
	SelfVideo               bool       `json:"self_video"`
	SessionID               string     `json:"session_id"`
	Suppress                bool       `json:"suppress"`
	UserID                  string     `json:"user_id"`
}
