// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// WebhookSlackEmbed
type WebhookSlackEmbed struct {
	AuthorIcon *string `json:"author_icon,omitempty"`
	AuthorLink *string `json:"author_link,omitempty"`
	AuthorName *string `json:"author_name,omitempty"`
	Color      *string `json:"color,omitempty"`
	Fields     []any   `json:"fields,omitempty"`
	Footer     *string `json:"footer,omitempty"`
	FooterIcon *string `json:"footer_icon,omitempty"`
	ImageURL   *string `json:"image_url,omitempty"`
	Pretext    *string `json:"pretext,omitempty"`
	Text       *string `json:"text,omitempty"`
	ThumbURL   *string `json:"thumb_url,omitempty"`
	Title      *string `json:"title,omitempty"`
	TitleLink  *string `json:"title_link,omitempty"`
	Ts         *int64  `json:"ts,omitempty"`
}

// WebhookSlackEmbedField
type WebhookSlackEmbedField struct {
	Inline *bool   `json:"inline,omitempty"`
	Name   *string `json:"name,omitempty"`
	Value  *string `json:"value,omitempty"`
}

// WebhookSourceChannel
type WebhookSourceChannel struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// WebhookSourceGuild
type WebhookSourceGuild struct {
	ID   string  `json:"id"`
	Icon *string `json:"icon,omitempty"`
	Name string  `json:"name"`
}

// WebhookTypes
type WebhookTypes int

const (
	WebhookTypes1 WebhookTypes = 1
	WebhookTypes2 WebhookTypes = 2
	WebhookTypes3 WebhookTypes = 3
)
