// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// WelcomeMessage
type WelcomeMessage struct {
	AuthorIds []string `json:"author_ids"`
	Message   string   `json:"message"`
}

// WelcomeScreenPatchOptionsPartial
type WelcomeScreenPatchOptionsPartial struct {
	Description     *string `json:"description,omitempty"`
	Enabled         *bool   `json:"enabled,omitempty"`
	WelcomeChannels []any   `json:"welcome_channels,omitempty"`
}
