// Code generated by neuron-cli. DO NOT EDIT.
// Generated at: 2025-12-22T14:28:22-05:00

package models

// Widget
type Widget struct {
	ID            string  `json:"id"`
	Channels      []any   `json:"channels"`
	InstantInvite *string `json:"instant_invite,omitempty"`
	Members       []any   `json:"members"`
	Name          string  `json:"name"`
	PresenceCount int32   `json:"presence_count"`
}

// WidgetActivity
type WidgetActivity struct {
	Name string `json:"name"`
}

// WidgetChannel
type WidgetChannel struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Position int32  `json:"position"`
}

// WidgetImageStyles
type WidgetImageStyles string

const (
	WidgetImageStylesShield  WidgetImageStyles = "shield"
	WidgetImageStylesBanner1 WidgetImageStyles = "banner1"
	WidgetImageStylesBanner2 WidgetImageStyles = "banner2"
	WidgetImageStylesBanner3 WidgetImageStyles = "banner3"
	WidgetImageStylesBanner4 WidgetImageStyles = "banner4"
)

// WidgetMember
type WidgetMember struct {
	ID            string `json:"id"`
	Activity      any    `json:"activity,omitempty"`
	Avatar        any    `json:"avatar,omitempty"`
	AvatarURL     string `json:"avatar_url"`
	ChannelID     string `json:"channel_id,omitempty"`
	Deaf          bool   `json:"deaf,omitempty"`
	Discriminator string `json:"discriminator"`
	Mute          bool   `json:"mute,omitempty"`
	SelfDeaf      bool   `json:"self_deaf,omitempty"`
	SelfMute      bool   `json:"self_mute,omitempty"`
	Status        string `json:"status"`
	Suppress      bool   `json:"suppress,omitempty"`
	Username      string `json:"username"`
}

// WidgetSettings
type WidgetSettings struct {
	ChannelID any  `json:"channel_id,omitempty"`
	Enabled   bool `json:"enabled"`
}

// WidgetUserDiscriminator
type WidgetUserDiscriminator string

const (
	WidgetUserDiscriminator0000 WidgetUserDiscriminator = "0000"
)
